export const SERVICES = {
  home_scan: {
    branded: 'Home DNA Scan',
    generic: 'Home DNA Scan',
    display: 'Home DNA Scan',
    slug: '/home-scan',
    startingPrice: 99,
    priceUnit: 'flat',
    tagline: 'Know your home inside out.',
    description: 'A complete walkthrough of what your home needs. Your personalized maintenance roadmap. Add drone aerial scan for $249.',
    tiers: {
      standard: {
        name: 'Home DNA Scan Standard',
        price: 99,
        proPayout: 50, // $50 FLAT payout for ALL Home DNA Scan tiers
        description: 'Interior + exterior ground-level walkthrough with maintenance report',
        includes: [
          'Full interior room-by-room walkthrough with photos',
          'Exterior ground-level assessment (foundation, driveway, walkways, landscaping)',
          'Major systems check (AC age, water heater, electrical, plumbing)',
          'Cleanliness rating per room (1-10 scale)',
          'Foundation and structural visual check',
          'Personalized maintenance report',
          'One-tap booking for recommended services',
        ],
        estimatedDuration: '30 minutes',
        prosNeeded: 1,
      },
      aerial: {
        name: 'Home DNA Scan Aerial',
        price: 249,
        proPayout: 50, // $50 FLAT payout for ALL Home DNA Scan tiers
        description: 'Everything in Standard plus drone-powered roof, gutter, and exterior aerial scan',
        includes: [
          'Everything in Home DNA Scan Standard',
          'FAA Part 107 certified drone flyover',
          'Aerial roof condition scan (missing shingles, sagging, moss, flashing damage)',
          'Gutter blockage percentage estimate from above',
          'Chimney and vent inspection',
          'Tree overhang proximity to roof and power lines',
          'Siding and paint condition from aerial angle',
          'Pool enclosure / screen assessment',
          'Property drainage overview from aerial perspective',
          'Full aerial photo set, timestamped and GPS-tagged',
        ],
        estimatedDuration: '45 minutes (15 min drone + 30 min walkthrough)',
        prosNeeded: { default: 2, ifCombined: 1 },
      },
    },
    credit: {
      amount: 49,
      appliesTo: 'next booked service',
      expiresInDays: 90,
      stacksWithDiscounts: true,
      appliedBeforePercentageDiscount: true,
      onePerDwellScan: true,
      description: '$49 credit toward your next UpTend service',
    },
  },
  handyman: {
    branded: 'Handyman Services',
    generic: 'Handyman Services',
    display: 'Handyman Services',
    slug: '/fixit',
    startingPrice: 75,
    priceUnit: 'hourly',
    tagline: 'No task too small.',
    description: 'Assembly, mounting, repairs, painting, installations. Verified pros, 1-hour minimum, billed by the minute after.',
  },
  junk_removal: {
    branded: 'Junk Removal',
    generic: 'Junk Removal',
    display: 'Junk Removal',
    slug: '/bulksnap',
    startingPrice: 99,
    priceUnit: 'flat',
    tagline: 'Snap a photo. Bulk gone.',
    description: 'One item or a full truckload. We sort, haul, and track where everything goes.',
  },
  garage_cleanout: {
    branded: 'Garage Cleanout',
    generic: 'Garage Cleanout',
    display: 'Garage Cleanout',
    slug: '/garagereset',
    startingPrice: 129,
    priceUnit: 'flat',
    tagline: 'Your garage, returned to you.',
    description: 'Full sort, organize, donate coordination, and haul-away.',
  },
  moving_labor: {
    branded: 'Moving Labor',
    generic: 'Moving Labor',
    display: 'Moving Labor',
    slug: '/liftcrew',
    startingPrice: 65,
    priceUnit: 'hourly',
    tagline: 'Your crew, your schedule.',
    description: 'Loading, unloading, rearranging. Book the crew size you need.',
    subTypes: {
      furniture_moving: { name: 'Furniture Moving', price: 80, unit: 'per hour per Pro', description: 'In-home or local furniture moving with blankets & straps' },
      truck_unloading: { name: 'Truck/Pod Unloading', price: 80, unit: 'per hour per Pro', description: 'Unload your rental truck, pod, or trailer' },
      general_labor: { name: 'General Labor', price: 80, unit: 'per hour per Pro', description: 'Loading, unloading, rearranging — flexible muscle on demand' },
    },
  },
  home_cleaning: {
    branded: 'Home Cleaning',
    generic: 'Home Cleaning',
    display: 'Home Cleaning',
    slug: '/polishup',
    startingPrice: 99, // Still show "starting at $99" in marketing
    priceUnit: 'dynamic', // Flag that this uses the pricing engine
    pricingEngine: 'polishup_calculator',
    tagline: 'From chaos to calm.',
    description: 'Professional home cleaning — standard, deep, or move-out. Price based on your home size and clean type.',
    cleanTypes: ['standard', 'deep', 'move_out'],
  },
  carpet_cleaning: {
    branded: 'Carpet Cleaning',
    generic: 'Carpet Cleaning',
    display: 'Carpet Cleaning',
    slug: '/deepfiber',
    startingPrice: 50,
    priceUnit: 'per_room',
    tagline: 'Deep clean underfoot.',
    description: 'Professional hot water extraction deep cleaning for carpets and rugs.',
    minimumCharge: 100,
    tiers: {
      standard: { name: 'Standard Steam Clean', price: 50, unit: 'per room', description: 'Steam/hot water extraction, pre-treatment, vacuum' },
      deep_clean: { name: 'Deep Clean', price: 75, unit: 'per room', description: 'Standard + enzyme treatment, heavy soil agitation, slow dry pass' },
      pet_treatment: { name: 'Pet Treatment', price: 89, unit: 'per room', description: 'Deep clean + pet odor enzyme + sanitizer' },
      hallway: { name: 'Hallway', price: 25, unit: 'each', description: 'Hallway cleaning' },
      stairs: { name: 'Stairs (per flight)', price: 25, unit: 'per flight', description: 'Stairway cleaning per flight' },
      scotchgard: { name: 'Scotchgard/Protectant', price: 20, unit: 'per room', description: 'Stain protection add-on' },
      package_3br: { name: '3BR/2BA Standard Package', price: 129, unit: 'flat', description: 'All rooms + hallway' },
      package_4_5br: { name: '4-5BR Standard Package', price: 215, unit: 'flat', description: 'All rooms + hallways' },
    },
  },
  landscaping: {
    branded: 'Landscaping',
    generic: 'Landscaping',
    display: 'Landscaping',
    slug: '/freshcut',
    startingPrice: 59,
    priceUnit: 'flat',
    tagline: 'Your yard, perfected.',
    description: 'Lawn mowing, edging, trimming, and seasonal maintenance.',
    tiers: {
      // One-Time Services
      one_time_mow_quarter: { name: 'One-Time Mow (≤¼ acre)', price: 59, unit: 'one-time', description: 'Single mow, edge, and blow' },
      one_time_mow_half: { name: 'One-Time Mow (≤½ acre)', price: 89, unit: 'one-time', description: 'Single mow, edge, and blow for larger lots' },
      yard_cleanup: { name: 'Yard Cleanup', price: 149, unit: 'one-time', description: 'Overgrown lot, debris, trimming ($149–$299)' },
      // Recurring Monthly (billed monthly, service weekly)
      mow_and_go_quarter: { name: 'Mow & Go (≤¼ acre)', price: 99, unit: 'mo', description: 'Weekly mow + blow + edging along hardscapes' },
      mow_and_go_half: { name: 'Mow & Go (≤½ acre)', price: 149, unit: 'mo', description: 'Weekly mow + blow + edging along hardscapes' },
      full_service_quarter: { name: 'Full Service (≤¼ acre)', price: 159, unit: 'mo', description: 'Mow + edge + trim + blow + weed beds + hedge trim (monthly)' },
      full_service_half: { name: 'Full Service (≤½ acre)', price: 219, unit: 'mo', description: 'Mow + edge + trim + blow + weed beds + hedge trim (monthly)' },
      premium_quarter: { name: 'Premium (≤¼ acre)', price: 249, unit: 'mo', description: 'Full Service + seasonal flowers (quarterly) + mulch (2x/yr) + irrigation check' },
      premium_half: { name: 'Premium (≤½ acre)', price: 329, unit: 'mo', description: 'Full Service + seasonal flowers (quarterly) + mulch (2x/yr) + irrigation check' },
    },
  },
  gutter_cleaning: {
    branded: 'Gutter Cleaning',
    generic: 'Gutter Cleaning',
    display: 'Gutter Cleaning',
    slug: '/gutterflush',
    startingPrice: 129,
    priceUnit: 'flat',
    tagline: 'Clear gutters. Clear mind.',
    description: 'Single-story to multi-story. Inspected, cleaned, documented.',
    tiers: {
      '1_story': { name: '1-Story (up to 150 linear ft)', price: 129 },
      '1_story_large': { name: '1-Story Large (150-250 linear ft)', price: 179 },
      '2_story': { name: '2-Story (up to 150 linear ft)', price: 199 },
      '2_story_large': { name: '2-Story Large (150-250 linear ft)', price: 259 },
      '3_story': { name: '3-Story', price: 350 },
    },
    addOns: {
      gutter_guard: { name: 'Gutter guard install', pricePerLinearFt: { min: 4, max: 6 } },
      downspout_flush: { name: 'Downspout flush', priceEach: 15 },
      gutter_repair: { name: 'Gutter repair (minor)', price: 75 },
    },
  },
  pressure_washing: {
    branded: 'Pressure Washing',
    generic: 'Pressure Washing',
    display: 'Pressure Washing',
    slug: '/freshwash',
    startingPrice: 120,
    priceUnit: 'flat',
    tagline: 'See the difference instantly.',
    description: 'Driveways, walkways, house exteriors. See the difference in your before-and-after report.',
  },
  pool_cleaning: {
    branded: 'Pool Cleaning',
    generic: 'Pool Cleaning',
    display: 'Pool Cleaning',
    slug: '/poolspark',
    startingPrice: 99,
    priceUnit: 'monthly',
    tagline: 'Crystal clear, hassle free.',
    description: 'Weekly pool maintenance from chemical balancing to full equipment monitoring.',
    tiers: {
      basic: { name: 'Basic', price: 99, unit: 'mo', description: 'Weekly chemicals + skim surface + empty baskets' },
      standard: { name: 'Standard', price: 165, unit: 'mo', description: 'Basic + brush walls + vacuum + filter check' },
      full_service: { name: 'Full Service', price: 210, unit: 'mo', description: 'Standard + tile cleaning + equipment monitoring + filter cleaning' },
      deep_clean: { name: 'One-Time Deep Clean', price: 249, unit: 'one-time', description: 'Deep clean for neglected/green pools' },
    },
  },
  light_demolition: {
    branded: 'Light Demolition',
    generic: 'Light Demolition',
    display: 'Light Demolition',
    slug: '/teardown',
    startingPrice: 199,
    priceUnit: 'flat',
    tagline: 'Out with the old.',
    description: 'Sheds, decks, interior tear-outs. Permitted, tracked, disposed properly.',
  },
  // truck_unloading consolidated into moving_labor as a sub-type
} as const;

// Helper to get display name
export const getServiceDisplay = (key: keyof typeof SERVICES) => {
  const svc = SERVICES[key];
  return svc.display;
};
