export const SERVICES = {
  junk_removal: {
    branded: 'BulkSnap',
    generic: 'Junk Removal',
    display: 'BulkSnap™ (Junk Removal)',
    slug: '/bulksnap',
    startingPrice: 99,
    priceUnit: 'flat',
    tagline: 'Snap a photo. Bulk gone.',
    description: 'One item or a full truckload. We sort, haul, and track where everything goes.',
  },
  home_cleaning: {
    branded: 'PolishUp',
    generic: 'Home Cleaning',
    display: 'PolishUp™ (Home Cleaning)',
    slug: '/polishup',
    startingPrice: 99, // Still show "starting at $99" in marketing
    priceUnit: 'dynamic', // Flag that this uses the pricing engine
    pricingEngine: 'polishup_calculator',
    tagline: 'From chaos to calm.',
    description: 'Professional home cleaning — standard, deep, or move-out. Price based on your home size and clean type.',
    cleanTypes: ['standard', 'deep', 'move_out'],
  },
  pressure_washing: {
    branded: 'FreshWash',
    generic: 'Pressure Washing',
    display: 'FreshWash™ (Pressure Washing)',
    slug: '/freshwash',
    startingPrice: 120,
    priceUnit: 'flat',
    tagline: 'See the difference instantly.',
    description: 'Driveways, walkways, house exteriors. See the difference in your before-and-after report.',
  },
  gutter_cleaning: {
    branded: 'GutterFlush',
    generic: 'Gutter Cleaning',
    display: 'GutterFlush™ (Gutter Cleaning)',
    slug: '/gutterflush',
    startingPrice: 149,
    priceUnit: 'flat',
    tagline: 'Clear gutters. Clear mind.',
    description: 'Single-story to multi-story. Inspected, cleaned, documented.',
  },
  moving_labor: {
    branded: 'LiftCrew',
    generic: 'Moving Labor',
    display: 'LiftCrew™ (Moving Labor)',
    slug: '/liftcrew',
    startingPrice: 80,
    priceUnit: 'hourly',
    tagline: 'Your crew, your schedule.',
    description: 'Loading, unloading, rearranging. Book the crew size you need.',
  },
  light_demolition: {
    branded: 'TearDown',
    generic: 'Light Demolition',
    display: 'TearDown™ (Light Demolition)',
    slug: '/teardown',
    startingPrice: 199,
    priceUnit: 'flat',
    tagline: 'Out with the old.',
    description: 'Sheds, decks, interior tear-outs. Permitted, tracked, disposed properly.',
  },
  garage_cleanout: {
    branded: 'GarageReset',
    generic: 'Garage Cleanout',
    display: 'GarageReset™ (Garage Cleanout)',
    slug: '/garagereset',
    startingPrice: 299,
    priceUnit: 'flat',
    tagline: 'Your garage, returned to you.',
    description: 'Full sort, organize, donate coordination, and haul-away.',
  },
  truck_unloading: {
    branded: 'UnloadPro',
    generic: 'Truck Unloading',
    display: 'UnloadPro™ (Truck Unloading)',
    slug: '/unloadpro',
    startingPrice: 80,
    priceUnit: 'hourly',
    tagline: 'We handle the heavy lifting.',
    description: 'Moving truck, storage pod, delivery — your crew handles the heavy lifting.',
  },
  home_audit: {
    branded: 'DwellScan',
    generic: 'Home Audit',
    display: 'DwellScan™ (Home Audit)',
    slug: '/dwellscan',
    startingPrice: 49,
    priceUnit: 'flat',
    tagline: 'Know your home inside out.',
    description: 'A complete walkthrough of what your home needs. Your personalized maintenance roadmap. Add drone aerial scan for $149.',
    tiers: {
      standard: {
        name: 'DwellScan™ Standard',
        price: 49,
        proPayout: 25,
        description: 'Interior + exterior ground-level walkthrough with maintenance report',
        includes: [
          'Full interior room-by-room walkthrough with photos',
          'Exterior ground-level assessment (foundation, driveway, walkways, landscaping)',
          'Major systems check (AC age, water heater, electrical, plumbing)',
          'Cleanliness rating per room (1-10 scale)',
          'Foundation and structural visual check',
          'Personalized maintenance report',
          'One-tap booking for recommended services',
        ],
        estimatedDuration: '30 minutes',
        prosNeeded: 1,
      },
      aerial: {
        name: 'DwellScan™ Aerial',
        price: 149,
        proPayoutModels: {
          twoPro: { walkthrough: 25, drone: 55, uptendKeeps: 69 },
          onePro: { combined: 80, uptendKeeps: 69 },
        },
        description: 'Everything in Standard plus drone-powered roof, gutter, and exterior aerial scan',
        includes: [
          'Everything in DwellScan Standard',
          'FAA Part 107 certified drone flyover',
          'Aerial roof condition scan (missing shingles, sagging, moss, flashing damage)',
          'Gutter blockage percentage estimate from above',
          'Chimney and vent inspection',
          'Tree overhang proximity to roof and power lines',
          'Siding and paint condition from aerial angle',
          'Pool enclosure / screen assessment',
          'Property drainage overview from aerial perspective',
          'Full aerial photo set, timestamped and GPS-tagged',
        ],
        estimatedDuration: '45 minutes (15 min drone + 30 min walkthrough)',
        prosNeeded: { default: 2, ifCombined: 1 },
      },
    },
    credit: {
      amount: 49,
      appliesTo: 'next booked service',
      expiresInDays: 90,
      stacksWithDiscounts: true,
      appliedBeforePercentageDiscount: true,
      onePerDwellScan: true,
      description: '$49 credit toward your next UpTend service',
    },
  },
} as const;

// Helper to get display name with TM on first use
export const getServiceDisplay = (key: keyof typeof SERVICES, withTM = true) => {
  const svc = SERVICES[key];
  return withTM ? `${svc.branded}™ (${svc.generic})` : `${svc.branded} (${svc.generic})`;
};
