CREATE TABLE "ai_conversation_messages" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"conversation_id" varchar NOT NULL,
	"role" text NOT NULL,
	"content" text NOT NULL,
	"media_urls" text[],
	"media_content_types" text[],
	"detected_intent" text,
	"detected_service" text,
	"detected_urgency" text,
	"suggested_actions" jsonb,
	"property_context_snapshot" jsonb,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai_conversations" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"property_id" varchar,
	"title" text,
	"channel" text DEFAULT 'in_app' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"context_type" text,
	"referenced_appliance_id" varchar,
	"referenced_warranty_id" varchar,
	"referenced_service_request_id" varchar,
	"resulted_in_booking" boolean DEFAULT false,
	"resulted_in_warranty_claim" boolean DEFAULT false,
	"resulted_in_escalation" boolean DEFAULT false,
	"booking_service_request_id" varchar,
	"customer_rating" integer,
	"message_count" integer DEFAULT 0,
	"ai_model_used" text DEFAULT 'claude-sonnet',
	"total_tokens_used" integer DEFAULT 0,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"resolved_at" text
);
--> statement-breakpoint
CREATE TABLE "ai_estimates" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"request_id" varchar,
	"quote_method" varchar DEFAULT 'ai',
	"service_type" varchar,
	"photo_urls" text[],
	"video_url" text,
	"identified_items" text[],
	"estimated_volume_cubic_ft" real,
	"recommended_load_size" text,
	"confidence" real,
	"suggested_price" real,
	"suggested_price_min" real,
	"suggested_price_max" real,
	"reasoning" text,
	"raw_response" text,
	"manual_inputs" text,
	"requires_hitl_validation" boolean DEFAULT false,
	"validated_price" real,
	"validated_by" varchar,
	"total_sqft" real,
	"surfaces" text,
	"home_health_report" text,
	"uptend_services" text,
	"referral_recommendations" text,
	"priority_level" varchar,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai_marketing_content" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"service_type" text NOT NULL,
	"pro_user_id" varchar,
	"customer_id" varchar,
	"before_photo_url" text,
	"after_photo_url" text,
	"transformation_score" real,
	"post_caption" text,
	"post_hashtags" text[],
	"target_platforms" text[],
	"neighborhood" text,
	"zip_code" text,
	"city" text,
	"customer_share_link" text,
	"customer_share_credit" real DEFAULT 10,
	"customer_shared_at" text,
	"customer_share_platform" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"published_at" text,
	"published_platforms" text[],
	"impressions" integer DEFAULT 0,
	"engagements" integer DEFAULT 0,
	"click_throughs" integer DEFAULT 0,
	"bookings_from_post" integer DEFAULT 0,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai_safety_alerts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"hauler_id" varchar NOT NULL,
	"alert_type" text NOT NULL,
	"severity" text DEFAULT 'warning' NOT NULL,
	"description" text NOT NULL,
	"safety_instructions" text,
	"disposal_guide_url" text,
	"photo_url" text,
	"acknowledged" boolean DEFAULT false,
	"acknowledged_at" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai_triage_reports" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar,
	"requested_by" varchar,
	"photo_urls" text[] NOT NULL,
	"overall_classification" text NOT NULL,
	"confidence" real DEFAULT 0 NOT NULL,
	"inventory" text NOT NULL,
	"total_estimated_weight_lbs" real DEFAULT 0,
	"total_item_count" integer DEFAULT 0,
	"hazardous_item_count" integer DEFAULT 0,
	"donation_item_count" integer DEFAULT 0,
	"recyclable_item_count" integer DEFAULT 0,
	"guaranteed_price" real,
	"recommended_crew_size" integer DEFAULT 2,
	"recommended_vehicle_type" text,
	"special_equipment_needed" text[],
	"safety_warnings" text[],
	"raw_response" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "analytics_events" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar,
	"session_id" varchar,
	"event_type" text NOT NULL,
	"event_data" text,
	"device_type" text,
	"platform" text,
	"app_version" text,
	"referral_source" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_priority_slots" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slot_date" text NOT NULL,
	"slot_time" text NOT NULL,
	"is_same_day" boolean DEFAULT false,
	"is_weekend" boolean DEFAULT false,
	"reserved_for_app_until" text,
	"booked_by" varchar,
	"booking_source" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "appliance_scan_sessions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" varchar NOT NULL,
	"scanned_by" varchar NOT NULL,
	"scan_method" text NOT NULL,
	"status" text DEFAULT 'active',
	"started_at" text DEFAULT now() NOT NULL,
	"completed_at" text,
	"duration_seconds" integer,
	"total_scans" integer DEFAULT 0,
	"scans_processed" integer DEFAULT 0,
	"appliances_created" integer DEFAULT 0,
	"scans_needing_review" integer DEFAULT 0,
	"notes" text,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "appliance_scans" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" varchar NOT NULL,
	"scan_session_id" varchar,
	"photo_urls" text[],
	"location" text,
	"scan_method" text NOT NULL,
	"scanned_by" varchar,
	"scanned_at" text DEFAULT now() NOT NULL,
	"scan_session_sequence" integer,
	"ai_processing_status" text DEFAULT 'uploaded' NOT NULL,
	"ai_processing_started_at" text,
	"ai_processing_completed_at" text,
	"ai_processing_duration_ms" integer,
	"ai_processing_error" text,
	"extracted_brand" text,
	"extracted_model" text,
	"extracted_serial_number" text,
	"extracted_category" text,
	"confidence_score" real,
	"confidence_breakdown" jsonb,
	"needs_review" boolean DEFAULT false,
	"reviewed_by" varchar,
	"reviewed_at" text,
	"user_confirmed" boolean DEFAULT false,
	"user_rejected" boolean DEFAULT false,
	"auto_confirmed" boolean DEFAULT false,
	"appliance_created" boolean DEFAULT false,
	"appliance_id" varchar,
	"pro_scan_bonus" boolean DEFAULT false,
	"pro_bonus_earned" boolean DEFAULT false,
	"pro_bonus_amount" real DEFAULT 1,
	"notes" text,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "approved_facilities" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"address" text NOT NULL,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"zip_code" text,
	"facility_type" text NOT NULL,
	"license_number" text,
	"phone" text,
	"latitude" real,
	"longitude" real,
	"is_active" boolean DEFAULT true,
	"is_blocked" boolean DEFAULT false,
	"block_reason" text,
	"created_at" text NOT NULL,
	"updated_at" text
);
--> statement-breakpoint
CREATE TABLE "audit_logs" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"actor_id" varchar NOT NULL,
	"actor_role" varchar NOT NULL,
	"action_type" varchar NOT NULL,
	"resource_target" varchar NOT NULL,
	"ip_address" varchar,
	"user_agent" varchar,
	"metadata" text,
	"timestamp" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "builder_partnerships" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"builder_name" text NOT NULL,
	"builder_company" text NOT NULL,
	"builder_license" text,
	"contact_name" text,
	"contact_email" text NOT NULL,
	"contact_phone" text,
	"service_states" text[],
	"service_cities" text[],
	"service_zip_codes" text[],
	"partnership_tier" text DEFAULT 'basic',
	"commission_rate" real,
	"referral_fee" real,
	"offers_dwellscan" boolean DEFAULT false,
	"offers_warranty_package" boolean DEFAULT false,
	"offers_maintenance_plan" boolean DEFAULT false,
	"custom_packages" jsonb,
	"total_properties" integer DEFAULT 0,
	"total_homeowners" integer DEFAULT 0,
	"total_revenue" real DEFAULT 0,
	"average_home_value" real,
	"closing_workflow_enabled" boolean DEFAULT false,
	"closing_day_handoff_protocol" text,
	"digital_welcome_packet" boolean DEFAULT false,
	"contract_start_date" text,
	"contract_end_date" text,
	"contract_document_url" text,
	"insurance_certificate_url" text,
	"logo_url" text,
	"website_url" text,
	"marketing_materials" text[],
	"status" text DEFAULT 'active',
	"is_verified" boolean DEFAULT false,
	"verified_at" text,
	"notes" text,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "bundling_suggestions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"customer_id" varchar NOT NULL,
	"suggested_service_type" text NOT NULL,
	"suggested_items" text,
	"reason" text NOT NULL,
	"estimated_additional_cost" real,
	"discount_percent" real DEFAULT 0,
	"accepted" boolean DEFAULT false,
	"accepted_at" text,
	"dismissed" boolean DEFAULT false,
	"dismissed_at" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "business_accounts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"business_name" text NOT NULL,
	"business_type" text NOT NULL,
	"tax_id" text,
	"billing_address" text,
	"billing_city" text,
	"billing_state" text,
	"billing_zip" text,
	"primary_contact_name" text,
	"primary_contact_phone" text,
	"primary_contact_email" text,
	"volume_discount_tier" text DEFAULT 'none',
	"monthly_job_target" integer,
	"invoicing_enabled" boolean DEFAULT false,
	"net_payment_terms" integer DEFAULT 0,
	"total_jobs_completed" integer DEFAULT 0,
	"total_spent" real DEFAULT 0,
	"account_type" text DEFAULT 'business',
	"community_name" text,
	"total_properties" integer DEFAULT 0,
	"referral_rate" real DEFAULT 0.1,
	"referral_program_active" boolean DEFAULT false,
	"first_ten_jobs_bonus" boolean DEFAULT true,
	"jobs_with_referral_paid" integer DEFAULT 0,
	"total_referral_fees_earned" real DEFAULT 0,
	"total_referral_fees_paid" real DEFAULT 0,
	"carbon_credit_balance" real DEFAULT 0,
	"carbon_credits_generated" real DEFAULT 0,
	"carbon_credits_sold" real DEFAULT 0,
	"carbon_credit_revenue" real DEFAULT 0,
	"stripe_connect_account_id" text,
	"stripe_connect_onboarding_complete" boolean DEFAULT false,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "business_team_members" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"business_account_id" varchar NOT NULL,
	"user_id" varchar NOT NULL,
	"role" text DEFAULT 'member' NOT NULL,
	"can_view_financials" boolean DEFAULT false,
	"can_manage_team" boolean DEFAULT false,
	"can_create_jobs" boolean DEFAULT true,
	"can_approve_payments" boolean DEFAULT false,
	"can_access_esg_reports" boolean DEFAULT true,
	"can_manage_properties" boolean DEFAULT false,
	"invited_by" varchar,
	"invitation_token" text,
	"invitation_status" text DEFAULT 'pending',
	"is_active" boolean DEFAULT true,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "carbon_credits" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"business_account_id" varchar,
	"service_request_id" varchar NOT NULL,
	"credits_generated" real NOT NULL,
	"credits_earned" real,
	"status" text DEFAULT 'pending',
	"calculation_method" text,
	"waste_weight_lbs" real,
	"landfill_diversion_rate" real,
	"certification_status" text DEFAULT 'pending',
	"certification_date" text,
	"certificate_url" text,
	"market_value" real,
	"sold_at" text,
	"sale_price" real,
	"buyer_info" text,
	"created_at" text DEFAULT now() NOT NULL,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "chat_messages" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"job_id" varchar NOT NULL,
	"sender_id" varchar NOT NULL,
	"content" text NOT NULL,
	"is_redacted" boolean DEFAULT false,
	"sent_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cleaning_checklists" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"room_type" text NOT NULL,
	"task_name" text NOT NULL,
	"completed" boolean DEFAULT false,
	"skipped" boolean DEFAULT false,
	"skip_reason" text,
	"completed_at" text,
	"created_at" text DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "compliance_receipts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"hauler_id" varchar NOT NULL,
	"service_request_id" varchar,
	"receipt_type" text NOT NULL,
	"vendor_name" text,
	"amount" real NOT NULL,
	"receipt_date" text NOT NULL,
	"receipt_image_url" text,
	"ai_extracted_data" text,
	"tax_deductible" boolean DEFAULT false,
	"category" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "conflict_shield_reports" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"requested_by" varchar,
	"photos_before" text[] NOT NULL,
	"photos_after" text[],
	"pre_existing_damage" text NOT NULL,
	"pre_existing_damage_count" integer DEFAULT 0,
	"new_damage_detected" boolean DEFAULT false,
	"new_damage" text,
	"confidence" real DEFAULT 0 NOT NULL,
	"summary" text NOT NULL,
	"recommendation" text,
	"raw_response" text,
	"status" text DEFAULT 'completed',
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "consultations" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar NOT NULL,
	"hauler_id" varchar,
	"status" varchar DEFAULT 'scheduled',
	"price" integer DEFAULT 4900,
	"is_credit_used" boolean DEFAULT false,
	"generated_treatment_plan" jsonb,
	"home_score_impact" integer DEFAULT 50,
	"scheduled_at" text,
	"completed_at" text,
	"created_at" text DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "deferred_jobs" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"consultation_id" varchar,
	"title" varchar NOT NULL,
	"estimated_price" integer,
	"reason" varchar,
	"nudge_count" integer DEFAULT 0,
	"next_nudge_date" text,
	"status" varchar DEFAULT 'pending',
	"photo_url" text,
	"created_at" text DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "demand_heatmap_data" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"latitude" real NOT NULL,
	"longitude" real NOT NULL,
	"zip_code" text,
	"city" text,
	"day_of_week" integer NOT NULL,
	"hour_of_day" integer NOT NULL,
	"demand_score" real DEFAULT 0 NOT NULL,
	"avg_job_value" real DEFAULT 0,
	"historical_job_count" integer DEFAULT 0,
	"service_type" text,
	"prediction_confidence" real DEFAULT 0.5,
	"last_updated" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dispatch_batches" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"batch_date" text NOT NULL,
	"region" text NOT NULL,
	"hauler_id" varchar,
	"job_ids" text NOT NULL,
	"total_distance_miles" real DEFAULT 0,
	"optimized_distance_miles" real DEFAULT 0,
	"deadhead_miles_saved" real DEFAULT 0,
	"co2_saved_lbs" real DEFAULT 0,
	"discount_offered" real DEFAULT 0,
	"status" text DEFAULT 'proposed',
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dispatch_recommendations" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"triage_report_id" varchar,
	"recommended_crew_size" integer DEFAULT 2 NOT NULL,
	"recommended_vehicle_type" text NOT NULL,
	"estimated_total_weight_lbs" real DEFAULT 0,
	"estimated_volume_cubic_ft" real DEFAULT 0,
	"estimated_duration_hours" real DEFAULT 2,
	"fuel_efficiency_score" real DEFAULT 50,
	"green_match_priority" boolean DEFAULT false,
	"reasoning" text NOT NULL,
	"matched_hauler_ids" text[],
	"status" text DEFAULT 'pending',
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "disposal_receipts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"hauler_id" varchar NOT NULL,
	"job_id" varchar,
	"receipt_image_url" text NOT NULL,
	"facility_name" text,
	"receipt_date" text,
	"amount_paid" real,
	"bonus_amount" real DEFAULT 20,
	"bonus_status" text DEFAULT 'pending',
	"ai_verified" boolean DEFAULT false,
	"ai_confidence" real,
	"ai_extracted_data" text,
	"rejection_reason" text,
	"receipt_hash" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "disposal_recommendations" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"item_name" text NOT NULL,
	"category" text NOT NULL,
	"estimated_weight_lbs" real DEFAULT 0,
	"destination_name" text,
	"destination_address" text,
	"estimated_value" real DEFAULT 0,
	"co2_avoided_lbs" real DEFAULT 0,
	"status" text DEFAULT 'pending',
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "disposal_records" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"job_verification_id" varchar NOT NULL,
	"item_description" text NOT NULL,
	"item_photo_url" text,
	"estimated_weight_lbs" real NOT NULL,
	"actual_weight_lbs" real,
	"category" text NOT NULL,
	"destination_name" text NOT NULL,
	"destination_type" text,
	"destination_address" text,
	"receipt_photo_url" text,
	"receipt_ocr_data" jsonb,
	"proof_type" text,
	"proof_verified" boolean DEFAULT false,
	"gps_coordinates" text,
	"timestamp" text DEFAULT now() NOT NULL,
	"carbon_offset_tons" real DEFAULT 0,
	"carbon_calculation_method" text,
	"donation_organization" text,
	"donation_receipt_number" text,
	"resale_platform" text,
	"resale_listing_url" text,
	"resale_listing_screenshot_url" text,
	"landfill_reason" text,
	"landfill_facility_name" text,
	"landfill_weight_ticket_url" text,
	"specialty_disposal_type" text,
	"specialty_facility_name" text,
	"specialty_disposal_certificate_url" text,
	"ai_suggested_category" text,
	"ai_confidence" real,
	"created_at" text DEFAULT now() NOT NULL,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "disputes" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"job_completion_id" varchar,
	"customer_id" varchar NOT NULL,
	"hauler_id" varchar NOT NULL,
	"reason" text NOT NULL,
	"description" text,
	"status" text DEFAULT 'open' NOT NULL,
	"photos_before" text[],
	"photos_after" text[],
	"damage_photos" text[],
	"ai_analysis_result" text,
	"ai_confidence" real,
	"ai_recommendation" text,
	"ai_analyzed_at" text,
	"admin_notes" text,
	"resolution" text,
	"refund_amount" real,
	"resolved_by" varchar,
	"resolved_at" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "document_scans" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"property_id" varchar,
	"document_url" text NOT NULL,
	"document_content_type" text,
	"original_filename" text,
	"document_type" text,
	"ai_confidence" real,
	"extracted_data" jsonb,
	"linked_warranty_id" varchar,
	"linked_insurance_id" varchar,
	"linked_health_event_id" varchar,
	"linked_appliance_id" varchar,
	"processing_status" text DEFAULT 'uploaded' NOT NULL,
	"ai_model_used" text,
	"processing_time_ms" integer,
	"error_message" text,
	"user_verified" boolean DEFAULT false,
	"user_corrected_data" jsonb,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"processed_at" text
);
--> statement-breakpoint
CREATE TABLE "dwellscan_credits" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar NOT NULL,
	"dwellscan_job_id" varchar NOT NULL,
	"credit_amount" integer DEFAULT 49 NOT NULL,
	"used" boolean DEFAULT false,
	"used_on_booking_id" varchar,
	"used_at" text,
	"created_at" text NOT NULL,
	"expires_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "email_verification_codes" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"code" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"verified" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "emergency_requests" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar NOT NULL,
	"emergency_type" text NOT NULL,
	"description" text,
	"photo_urls" text[],
	"address_line1" text NOT NULL,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"zip_code" text NOT NULL,
	"lat" real,
	"lng" real,
	"status" text DEFAULT 'searching' NOT NULL,
	"assigned_hauler_id" varchar,
	"pricing_multiplier" real DEFAULT 2 NOT NULL,
	"estimated_price" real,
	"eta_minutes" integer,
	"accepted_at" text,
	"completed_at" text,
	"service_request_id" varchar,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "environmental_certificates" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"customer_id" varchar NOT NULL,
	"certificate_number" varchar NOT NULL,
	"recycled_percent" integer DEFAULT 0 NOT NULL,
	"donated_percent" integer DEFAULT 0 NOT NULL,
	"landfilled_percent" integer DEFAULT 0 NOT NULL,
	"facilities" text[],
	"facility_types" text[],
	"total_weight_lbs" real,
	"recycled_weight_lbs" real,
	"donated_weight_lbs" real,
	"landfilled_weight_lbs" real,
	"haul_distance_miles" real,
	"carbon_footprint_lbs" real,
	"carbon_offset_purchased" boolean DEFAULT true,
	"carbon_offset_cost" real,
	"issued_at" text NOT NULL,
	"expires_at" text,
	"verification_url" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "esg_impact_logs" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"hauler_id" varchar,
	"customer_id" varchar,
	"carbon_footprint_lbs" real DEFAULT 0 NOT NULL,
	"carbon_offset_cost" real DEFAULT 0,
	"carbon_offset_purchased" boolean DEFAULT false,
	"haul_distance_miles" real DEFAULT 0,
	"total_weight_lbs" real DEFAULT 0,
	"disposal_breakdown" text,
	"ai_categorization" text,
	"recycled_weight_lbs" real DEFAULT 0,
	"recycled_lbs" real DEFAULT 0,
	"donated_weight_lbs" real DEFAULT 0,
	"donated_lbs" real DEFAULT 0,
	"landfilled_weight_lbs" real DEFAULT 0,
	"landfilled_lbs" real DEFAULT 0,
	"e_waste_weight_lbs" real DEFAULT 0,
	"ewasted_lbs" real DEFAULT 0,
	"carbon_saved_lbs" real DEFAULT 0,
	"diversion_rate" real DEFAULT 0,
	"trees_equivalent" real DEFAULT 0,
	"water_saved_gallons" real DEFAULT 0,
	"energy_saved_kwh" real DEFAULT 0,
	"service_type" text,
	"methane_factor_applied" boolean DEFAULT false,
	"methane_co2_equivalent_lbs" real DEFAULT 0,
	"metal_diverted_lbs" real DEFAULT 0,
	"avoided_emissions_kg" real DEFAULT 0,
	"seer_rating_old" real,
	"seer_rating_new" real,
	"cleaner_type" text,
	"water_used_gallons" real DEFAULT 0,
	"routing_savings_kg" real DEFAULT 0,
	"routing_savings_pct" real DEFAULT 0,
	"tax_credit_alerts" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "esg_reports" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"business_account_id" varchar NOT NULL,
	"report_month" integer NOT NULL,
	"report_year" integer NOT NULL,
	"total_jobs_count" integer DEFAULT 0,
	"co2_saved_kg" real DEFAULT 0,
	"landfill_diversion_lbs" real DEFAULT 0,
	"tax_credits_unlocked_usd" real DEFAULT 0,
	"water_saved_gallons" real DEFAULT 0,
	"energy_saved_kwh" real DEFAULT 0,
	"total_carbon_footprint_lbs" real DEFAULT 0,
	"deadhead_miles_saved" real DEFAULT 0,
	"circular_economy_lbs" real DEFAULT 0,
	"audit_ready" boolean DEFAULT false,
	"report_data" text,
	"generated_at" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fraud_alerts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar,
	"pro_user_id" varchar NOT NULL,
	"alert_type" text NOT NULL,
	"severity" text NOT NULL,
	"evidence" jsonb,
	"ai_confidence" real,
	"ai_explanation" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"reviewed_by" varchar,
	"reviewed_at" text,
	"review_notes" text,
	"action_taken" text,
	"affected_customer_ids" text[],
	"refund_issued" boolean DEFAULT false,
	"refund_amount" real,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "guarantee_claims" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"customer_id" varchar NOT NULL,
	"reason" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"amount" real,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"resolved_at" text,
	"resolved_by" varchar,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "hauler_certifications" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"hauler_id" varchar NOT NULL,
	"type" varchar DEFAULT 'home_estimator',
	"skill_type" varchar DEFAULT 'core_safety',
	"status" varchar DEFAULT 'active',
	"is_active" boolean DEFAULT true,
	"earned_at" text DEFAULT now(),
	"expires_at" text,
	"quiz_score" integer DEFAULT 100,
	"accuracy_rating" integer DEFAULT 100
);
--> statement-breakpoint
CREATE TABLE "hauler_penalties" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"hauler_id" varchar NOT NULL,
	"request_id" varchar,
	"reason" text NOT NULL,
	"amount" real DEFAULT 25 NOT NULL,
	"status" text DEFAULT 'assessed' NOT NULL,
	"stripe_payment_intent_id" text,
	"charged_at" text,
	"waived_at" text,
	"waived_reason" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hauler_profiles" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"company_name" text NOT NULL,
	"bio" text,
	"vehicle_type" text NOT NULL,
	"capacity" text NOT NULL,
	"service_types" text[] DEFAULT ARRAY['junk_removal', 'furniture_moving', 'garage_cleanout', 'estate_cleanout', 'pressure_washing', 'gutter_cleaning', 'moving_labor', 'light_demolition', 'home_consultation', 'home_cleaning', 'pool_cleaning', 'landscaping', 'carpet_cleaning']::text[],
	"capabilities" text[] DEFAULT ARRAY[]::text[],
	"offers_labor_only" boolean DEFAULT false,
	"service_radius" integer DEFAULT 25 NOT NULL,
	"rating" real DEFAULT 5,
	"review_count" integer DEFAULT 0,
	"jobs_completed" integer DEFAULT 0,
	"years_in_business" integer DEFAULT 1,
	"is_available" boolean DEFAULT false,
	"last_checked_in" text,
	"current_lat" real,
	"current_lng" real,
	"hourly_rate" real DEFAULT 75,
	"verified" boolean DEFAULT false,
	"insurance_coverage" text DEFAULT '$1M',
	"phone" text,
	"website" text,
	"facebook_url" text,
	"instagram_url" text,
	"twitter_url" text,
	"yelp_url" text,
	"stripe_account_id" text,
	"stripe_onboarding_complete" boolean DEFAULT false,
	"incident_stripe_customer_id" text,
	"incident_payment_method_id" text,
	"has_card_on_file" boolean DEFAULT false,
	"background_check_status" text DEFAULT 'pending',
	"background_check_id" text,
	"background_check_completed_at" text,
	"can_accept_jobs" boolean DEFAULT false,
	"active_vehicle_id" varchar,
	"active_travel_radius" integer DEFAULT 25,
	"pycker_tier" text DEFAULT 'independent',
	"has_insurance" boolean DEFAULT false,
	"insurance_verified_at" text,
	"has_business_license" boolean DEFAULT false,
	"business_license_verified_at" text,
	"drone_certified" boolean DEFAULT false,
	"walkthrough_qualified" boolean DEFAULT true,
	"can_do_combined_dwellscan" boolean DEFAULT false,
	"payout_percentage" real DEFAULT 0.75,
	"is_verified_llc" boolean DEFAULT false,
	"five_star_job_count" real DEFAULT 0,
	"loyalty_priority_boost" boolean DEFAULT false,
	"rebate_balance" real DEFAULT 0,
	"languages_spoken" text[] DEFAULT ARRAY['en']::text[],
	"profile_photo_url" text,
	"drivers_license_photo_url" text,
	"selfie_photo_url" text,
	"id_photo_url" text,
	"general_liability_provider" text,
	"general_liability_policy_number" text,
	"general_liability_expiration" text,
	"general_liability_document_url" text,
	"vehicle_insurance_provider" text,
	"vehicle_insurance_policy_number" text,
	"vehicle_insurance_expiration" text,
	"vehicle_insurance_document_url" text,
	"has_own_liability_insurance" boolean DEFAULT false,
	"liability_insurance_certificate_url" text,
	"liability_insurance_verified_at" text,
	"insurance_surcharge_waived" boolean DEFAULT false,
	"nda_accepted_at" text,
	"nda_version" text,
	"nda_ip_address" text,
	"nda_signature" text,
	"level" integer DEFAULT 1,
	"xp_points" integer DEFAULT 0,
	"five_star_rating_count" integer DEFAULT 0,
	"is_consultant_eligible" boolean DEFAULT false,
	"commission_rate" integer DEFAULT 0,
	"supported_services" jsonb DEFAULT '["junk_removal"]'::jsonb,
	"has_pressure_washer" boolean DEFAULT false,
	"has_tall_ladder" boolean DEFAULT false,
	"has_demo_tools" boolean DEFAULT false,
	"is_certified" boolean DEFAULT false,
	"certified_at" text,
	"rookie_jobs_completed" integer DEFAULT 0,
	"is_rookie_mode" boolean DEFAULT true,
	"fun_fact" text,
	"video_intro_url" text,
	"safety_code" text,
	"landscaping_certified" boolean DEFAULT false,
	"lawn_equipment" jsonb DEFAULT '{}'::jsonb,
	"carpet_certified" boolean DEFAULT false,
	"has_truck_mount" boolean DEFAULT false,
	"same_day_available" boolean DEFAULT false,
	"same_day_radius" integer DEFAULT 15
);
--> statement-breakpoint
CREATE TABLE "hauler_reviews" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"hauler_id" varchar NOT NULL,
	"customer_id" varchar NOT NULL,
	"service_request_id" varchar NOT NULL,
	"rating" integer NOT NULL,
	"title" text,
	"comment" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hauler_risk_profile" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"hauler_id" varchar NOT NULL,
	"ghost_incidents" integer DEFAULT 0,
	"keywords_detected" integer DEFAULT 0,
	"risk_score" integer DEFAULT 0,
	"last_incident_at" text,
	CONSTRAINT "hauler_risk_profile_hauler_id_unique" UNIQUE("hauler_id")
);
--> statement-breakpoint
CREATE TABLE "hoa_properties" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"business_account_id" varchar NOT NULL,
	"address" text NOT NULL,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"zip_code" text NOT NULL,
	"owner_name" text,
	"owner_email" text,
	"owner_phone" text,
	"marketing_consent" boolean DEFAULT false,
	"consent_date" text,
	"consent_method" text,
	"move_in_date" text,
	"status" text DEFAULT 'active',
	"is_active" boolean DEFAULT true,
	"notes" text,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text
);
--> statement-breakpoint
CREATE TABLE "hoa_referral_payments" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"business_account_id" varchar NOT NULL,
	"service_request_id" varchar NOT NULL,
	"property_id" varchar,
	"service_type" text,
	"job_total" real NOT NULL,
	"job_amount" real,
	"referral_rate" real NOT NULL,
	"commission_rate" real,
	"referral_amount" real NOT NULL,
	"commission_amount" real,
	"status" text DEFAULT 'pending',
	"paid_at" text,
	"stripe_transfer_id" text,
	"created_at" text DEFAULT now() NOT NULL,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "hoa_violations" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"business_account_id" varchar NOT NULL,
	"property_id" varchar NOT NULL,
	"violation_type" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"due_date" text,
	"deadline" text,
	"document_url" text,
	"photos" text[],
	"status" text DEFAULT 'submitted' NOT NULL,
	"service_request_id" varchar,
	"submitted_by" varchar,
	"submitted_at" text DEFAULT now() NOT NULL,
	"contacted_owner_at" text,
	"owner_responded_at" text,
	"scheduled_at" text,
	"resolved_at" text,
	"notes" text,
	"urgency" text DEFAULT 'normal',
	"severity" text
);
--> statement-breakpoint
CREATE TABLE "home_appliances" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"home_profile_id" varchar NOT NULL,
	"name" text NOT NULL,
	"brand" text,
	"model" text,
	"purchase_date" text,
	"warranty_expiry" text,
	"last_service_date" text,
	"notes" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "home_inventory" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar NOT NULL,
	"service_request_id" varchar,
	"consultation_id" varchar,
	"item_name" varchar NOT NULL,
	"category" varchar,
	"estimated_value" integer,
	"confidence_score" integer,
	"brand_detected" varchar,
	"condition" varchar,
	"condition_notes" text,
	"photo_url" text,
	"verification_photo_url" text,
	"resale_status" varchar DEFAULT 'active',
	"resale_listing_url" text,
	"resale_description" text,
	"generated_at" text NOT NULL,
	"verified_at" text
);
--> statement-breakpoint
CREATE TABLE "home_profiles" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar NOT NULL,
	"address" text NOT NULL,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"zip" text NOT NULL,
	"home_type" text DEFAULT 'single_family' NOT NULL,
	"square_footage" text,
	"year_built" text,
	"bedrooms" text,
	"bathrooms" text,
	"lot_size" text,
	"photo_url" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "home_service_history" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"home_profile_id" varchar NOT NULL,
	"service_type" text NOT NULL,
	"provider" text,
	"date" text NOT NULL,
	"cost" text,
	"notes" text,
	"receipt_url" text,
	"warranty_expiry" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "insurance_partners" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"carrier_name" text NOT NULL,
	"carrier_code" text,
	"am_best_rating" text,
	"contact_name" text,
	"contact_email" text NOT NULL,
	"contact_phone" text,
	"licensed_states" text[] NOT NULL,
	"service_zip_codes" text[],
	"offers_homeowners" boolean DEFAULT true,
	"offers_flood" boolean DEFAULT false,
	"offers_windstorm" boolean DEFAULT false,
	"offers_umbrella" boolean DEFAULT false,
	"maintenance_discount" boolean DEFAULT false,
	"maintenance_discount_pct" real,
	"dwellscan_discount" boolean DEFAULT false,
	"dwellscan_discount_pct" real,
	"warranty_discount" boolean DEFAULT false,
	"warranty_discount_pct" real,
	"api_enabled" boolean DEFAULT false,
	"api_endpoint" text,
	"api_key" text,
	"webhook_url" text,
	"total_policies" integer DEFAULT 0,
	"total_premium_volume" real DEFAULT 0,
	"average_discount" real,
	"claim_approval_rate" real,
	"commission_rate" real,
	"referral_fee" real,
	"total_revenue" real DEFAULT 0,
	"partnership_tier" text DEFAULT 'standard',
	"contract_start_date" text,
	"contract_end_date" text,
	"contract_document_url" text,
	"logo_url" text,
	"website_url" text,
	"quote_url" text,
	"status" text DEFAULT 'active',
	"is_verified" boolean DEFAULT false,
	"verified_at" text,
	"notes" text,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now(),
	CONSTRAINT "insurance_partners_carrier_code_unique" UNIQUE("carrier_code")
);
--> statement-breakpoint
CREATE TABLE "inventory_estimates" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar,
	"user_id" varchar NOT NULL,
	"initiated_by" text NOT NULL,
	"service_type" text NOT NULL,
	"video_url" text,
	"frame_urls" text[],
	"photo_urls" text[],
	"room_inventories" jsonb,
	"total_items" integer,
	"total_estimated_weight" real,
	"estimated_truck_percentage" real,
	"estimated_truck_loads" real,
	"estimated_pros_needed" integer,
	"estimated_hours" real,
	"generated_price_min" real,
	"generated_price_max" real,
	"price_breakdown" jsonb,
	"junk_categorization" jsonb,
	"ai_model_used" text,
	"processing_time_ms" integer,
	"total_frames_analyzed" integer,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "job_adjustments" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"hauler_id" varchar NOT NULL,
	"adjustment_type" text NOT NULL,
	"item_id" text,
	"item_name" text NOT NULL,
	"quantity" integer DEFAULT 1,
	"price_change" real NOT NULL,
	"reason" text,
	"photo_urls" text[],
	"status" text DEFAULT 'pending' NOT NULL,
	"customer_approved_at" text,
	"customer_declined_at" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "job_completions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"hauler_id" varchar NOT NULL,
	"arrived_at_pickup" boolean DEFAULT false,
	"arrived_at_pickup_at" text,
	"items_verified" boolean DEFAULT false,
	"items_verified_at" text,
	"work_completed" boolean DEFAULT false,
	"work_completed_at" text,
	"photos_before" text[],
	"photos_after" text[],
	"pycker_notes" text,
	"original_quote" real NOT NULL,
	"adjustments_total" real DEFAULT 0,
	"final_amount" real NOT NULL,
	"payment_captured" boolean DEFAULT false,
	"payment_captured_at" text,
	"stripe_charge_id" text,
	"customer_confirmed_at" text,
	"customer_rating" integer,
	"customer_feedback" text,
	"has_dispute" boolean DEFAULT false,
	"dispute_reason" text,
	"dispute_resolved_at" text,
	"dispute_resolution" text,
	"created_at" text NOT NULL,
	"updated_at" text,
	CONSTRAINT "job_completions_service_request_id_unique" UNIQUE("service_request_id")
);
--> statement-breakpoint
CREATE TABLE "job_crew_assignments" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"hauler_id" varchar NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"accepted_at" text,
	"declined_at" text,
	"cancelled_at" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "job_quality_assessments" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"pro_user_id" varchar NOT NULL,
	"service_type" text NOT NULL,
	"before_photo_urls" text[],
	"after_photo_urls" text[],
	"ai_quality_score" real,
	"ai_analysis" text,
	"issues_detected" jsonb,
	"checklist_compliance_rate" real,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "job_verification" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"before_photos" text[],
	"before_photos_timestamp" text,
	"before_photos_gps" text,
	"before_photos_ai_analysis" jsonb,
	"after_photos" text[],
	"after_photos_timestamp" text,
	"after_photos_gps" text,
	"after_photos_ai_analysis" jsonb,
	"verification_status" text DEFAULT 'pending',
	"steps_completed" jsonb DEFAULT '{"beforePhotos": false, "itemTracking": false, "afterPhotos": false, "receipts": false, "customerConfirmation": false}',
	"started_at" text,
	"completed_at" text,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now(),
	"total_weight_lbs" real DEFAULT 0,
	"total_recycled_lbs" real DEFAULT 0,
	"total_donated_lbs" real DEFAULT 0,
	"total_resold_lbs" real DEFAULT 0,
	"total_landfilled_lbs" real DEFAULT 0,
	"total_specialty_lbs" real DEFAULT 0,
	"diversion_rate" real DEFAULT 0,
	"carbon_offset_tons" real DEFAULT 0,
	"carbon_credit_value" real DEFAULT 0,
	"cleanliness_score_before" real,
	"cleanliness_score_after" real,
	"customer_confirmed_at" text,
	"customer_feedback" text,
	"customer_issues_flagged" boolean DEFAULT false,
	"auto_approved_at" text,
	"admin_override_by" varchar,
	"admin_override_reason" text,
	"admin_override_at" text,
	CONSTRAINT "job_verification_service_request_id_unique" UNIQUE("service_request_id")
);
--> statement-breakpoint
CREATE TABLE "launch_notifications" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"city" text,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "launch_notifications_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "location_history" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"job_id" varchar,
	"lat" real NOT NULL,
	"lng" real NOT NULL,
	"accuracy" real,
	"heading" real,
	"speed" real,
	"recorded_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "loyalty_accounts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"current_points" integer DEFAULT 0,
	"lifetime_points" integer DEFAULT 0,
	"current_tier" text DEFAULT 'bronze' NOT NULL,
	"tier_expires_at" text,
	"total_jobs_completed" integer DEFAULT 0,
	"total_spent" real DEFAULT 0,
	"referral_bonus_earned" real DEFAULT 0,
	"last_points_earned_at" text,
	"created_at" text NOT NULL,
	CONSTRAINT "loyalty_accounts_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "loyalty_rewards" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"points_cost" integer NOT NULL,
	"reward_type" text NOT NULL,
	"discount_amount" real,
	"discount_percent" real,
	"minimum_tier" text DEFAULT 'bronze',
	"is_active" boolean DEFAULT true,
	"usage_limit" integer,
	"current_usage_count" integer DEFAULT 0,
	"valid_from" text,
	"valid_until" text
);
--> statement-breakpoint
CREATE TABLE "loyalty_transactions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"loyalty_account_id" varchar NOT NULL,
	"type" text NOT NULL,
	"points" integer NOT NULL,
	"description" text,
	"service_request_id" varchar,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "marketplace_items" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"pro_id" varchar NOT NULL,
	"service_request_id" varchar,
	"title" varchar NOT NULL,
	"description" text,
	"price" integer NOT NULL,
	"photos" text[],
	"category" varchar,
	"condition" varchar,
	"status" varchar DEFAULT 'available',
	"posted_at" text DEFAULT now(),
	"sold_at" text,
	"buyer_id" varchar,
	"views" integer DEFAULT 0,
	"location" varchar
);
--> statement-breakpoint
CREATE TABLE "match_attempts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"request_id" varchar NOT NULL,
	"hauler_id" varchar NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"quoted_price" real,
	"eta_minutes" integer,
	"expires_at" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mileage_logs" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"hauler_id" varchar NOT NULL,
	"service_request_id" varchar,
	"start_address" text,
	"end_address" text,
	"distance_miles" real NOT NULL,
	"purpose" text DEFAULT 'business',
	"trip_date" text NOT NULL,
	"irs_rate_cents_per_mile" real DEFAULT 67,
	"deduction_amount" real DEFAULT 0,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "move_in_plans" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"property_id" varchar NOT NULL,
	"source" text DEFAULT 'self_reported' NOT NULL,
	"builder_partnership_id" varchar,
	"move_in_date" text,
	"property_type" text,
	"sqft" integer,
	"year_built" integer,
	"has_pool" boolean DEFAULT false,
	"has_lawn" boolean DEFAULT true,
	"climate_zone" text,
	"lot_size_sqft" integer,
	"plan_title" text,
	"plan_summary" text,
	"week1_tasks" jsonb,
	"month1_tasks" jsonb,
	"month2_tasks" jsonb,
	"month3_tasks" jsonb,
	"ongoing_recurring" jsonb,
	"recommended_bundles" jsonb,
	"total_estimated_cost_90_days" real,
	"total_estimated_savings" real,
	"tasks_completed" integer DEFAULT 0,
	"total_tasks" integer DEFAULT 0,
	"completion_percentage" real DEFAULT 0,
	"total_booked" real DEFAULT 0,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "neighborhood_intelligence_reports" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"zip_code" text NOT NULL,
	"neighborhood" text,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"report_period" text NOT NULL,
	"period_start" text NOT NULL,
	"period_end" text NOT NULL,
	"total_properties_analyzed" integer NOT NULL,
	"total_jobs_analyzed" integer NOT NULL,
	"total_appliances_analyzed" integer DEFAULT 0,
	"average_health_score" real,
	"health_score_distribution" jsonb,
	"top_maintenance_issues" jsonb,
	"appliance_age_profiles" jsonb,
	"failure_rate_insights" jsonb,
	"warranty_gap_analysis" jsonb,
	"service_demand_by_type" jsonb,
	"seasonal_patterns" jsonb,
	"average_spend_per_home" real,
	"build_year_distribution" jsonb,
	"builder_quality_indicators" jsonb,
	"avg_diversion_rate" real,
	"avg_co2_saved_per_job" real,
	"sustainability_trend" text,
	"report_pdf_url" text,
	"is_public" boolean DEFAULT false,
	"licensed_to_partners" text[],
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "neighborhood_members" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"neighborhood_id" varchar NOT NULL,
	"customer_id" varchar NOT NULL,
	"joined_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "neighborhood_recommendations" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"neighborhood_id" varchar NOT NULL,
	"customer_id" varchar NOT NULL,
	"hauler_id" varchar NOT NULL,
	"service_type" text NOT NULL,
	"rating" integer NOT NULL,
	"review" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "neighborhoods" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"zip_code" text NOT NULL,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"member_count" integer DEFAULT 0 NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notification_queue" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"property_id" varchar,
	"notification_type" text NOT NULL,
	"channel" text NOT NULL,
	"priority" text DEFAULT 'normal',
	"title" text NOT NULL,
	"message" text NOT NULL,
	"action_text" text,
	"action_url" text,
	"warranty_id" varchar,
	"insurance_policy_id" varchar,
	"maintenance_task_id" varchar,
	"appliance_id" varchar,
	"health_event_id" varchar,
	"metadata" jsonb,
	"scheduled_for" text,
	"expires_at" text,
	"status" text DEFAULT 'pending',
	"sent_at" text,
	"delivered_at" text,
	"opened_at" text,
	"clicked_at" text,
	"push_notification_id" text,
	"email_message_id" text,
	"sms_message_id" text,
	"failure_reason" text,
	"retry_count" integer DEFAULT 0,
	"max_retries" integer DEFAULT 3,
	"is_read" boolean DEFAULT false,
	"is_clicked" boolean DEFAULT false,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "partner_bookings" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"partner_id" varchar NOT NULL,
	"service_request_id" varchar,
	"service_type" text NOT NULL,
	"client_name" text NOT NULL,
	"client_phone" text,
	"client_email" text,
	"address" text NOT NULL,
	"city" text,
	"state" text,
	"zip" text,
	"preferred_date" text,
	"original_amount" text,
	"discount_amount" text,
	"final_amount" text,
	"commission_rate" text,
	"notes" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "partner_referrals" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"home_health_audit_id" varchar,
	"customer_id" varchar NOT NULL,
	"pro_id" varchar NOT NULL,
	"partner_id" varchar NOT NULL,
	"category" varchar NOT NULL,
	"description" text,
	"estimated_value" integer,
	"status" varchar DEFAULT 'pending',
	"completed_at" text,
	"referral_amount" integer,
	"commission_amount" integer,
	"commission_paid_at" text,
	"customer_notes" text,
	"created_at" text DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "partners" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_name" text NOT NULL,
	"contact_name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text NOT NULL,
	"password_hash" text,
	"type" text DEFAULT 'other' NOT NULL,
	"api_key" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "password_reset_tokens" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"token" varchar NOT NULL,
	"expires_at" timestamp NOT NULL,
	"used" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "password_reset_tokens_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "photo_quote_requests" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"property_id" varchar,
	"photo_urls" text[] NOT NULL,
	"photo_content_types" text[],
	"ai_classified_service" text,
	"ai_classified_category" text,
	"ai_confidence" real,
	"ai_description" text,
	"estimated_price_min" real,
	"estimated_price_max" real,
	"estimated_scope" text,
	"estimated_duration" text,
	"additional_services" jsonb,
	"status" text DEFAULT 'pending' NOT NULL,
	"converted_to_service_request_id" varchar,
	"converted_at" text,
	"source" text DEFAULT 'in_app',
	"ai_model_used" text,
	"processing_time_ms" integer,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform_sustainability_stats" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"total_jobs_audited" integer DEFAULT 0,
	"total_co2_saved_kg" real DEFAULT 0,
	"total_co2_emitted_kg" real DEFAULT 0,
	"total_landfill_diverted_lbs" real DEFAULT 0,
	"total_recycled_lbs" real DEFAULT 0,
	"total_donated_lbs" real DEFAULT 0,
	"total_ewaste_lbs" real DEFAULT 0,
	"total_landfilled_lbs" real DEFAULT 0,
	"trees_equivalent" real DEFAULT 0,
	"water_saved_gallons" real DEFAULT 0,
	"energy_saved_kwh" real DEFAULT 0,
	"avg_diversion_rate" real DEFAULT 0,
	"deadhead_miles_saved" real DEFAULT 0,
	"total_carbon_offsets_purchased" real DEFAULT 0,
	"last_audited_at" text,
	"updated_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "portfolio_health_reports" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"business_account_id" varchar NOT NULL,
	"generated_by_user_id" varchar,
	"property_ids" text[] NOT NULL,
	"total_properties" integer NOT NULL,
	"portfolio_health_score" real,
	"lowest_scoring_property_id" varchar,
	"highest_scoring_property_id" varchar,
	"score_distribution" jsonb,
	"overdue_maintenance_items" jsonb,
	"aging_appliance_alerts" jsonb,
	"missing_dwellscans" jsonb,
	"action_plan" jsonb,
	"total_recommended_spend" real,
	"projected_health_score_after_actions" real,
	"portfolio_esg_summary" jsonb,
	"report_pdf_url" text,
	"status" text DEFAULT 'generating' NOT NULL,
	"delivered_at" text,
	"actions_booked" integer DEFAULT 0,
	"total_booked_value" real DEFAULT 0,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"report_period" text
);
--> statement-breakpoint
CREATE TABLE "pricing_rates" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_type" text NOT NULL,
	"vehicle_type" text,
	"load_size" text NOT NULL,
	"base_rate" real NOT NULL,
	"per_mile_rate" real DEFAULT 1 NOT NULL,
	"min_price" real DEFAULT 75 NOT NULL,
	"max_price" real,
	"is_active" boolean DEFAULT true
);
--> statement-breakpoint
CREATE TABLE "pro_quality_scores" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"pro_user_id" varchar NOT NULL,
	"service_type" text NOT NULL,
	"total_jobs_scored" integer DEFAULT 0,
	"average_quality_score" real,
	"average_customer_rating" real,
	"quality_trend" text,
	"trend_change_date" text,
	"cleanliness_score" real,
	"thoroughness_score" real,
	"before_after_improvement_score" real,
	"flagged_issues" jsonb,
	"recommended_training" jsonb,
	"training_completed_modules" text[],
	"quality_boost" real DEFAULT 0,
	"last_updated" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pro_route_optimizations" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"pro_user_id" varchar NOT NULL,
	"route_date" text NOT NULL,
	"assigned_job_ids" text[] NOT NULL,
	"original_order" jsonb,
	"optimized_order" jsonb,
	"original_total_miles" real,
	"optimized_total_miles" real,
	"miles_saved" real,
	"estimated_time_saved_minutes" integer,
	"co2_saved" real,
	"nearby_upsell_opportunities" jsonb,
	"upsells_sent" integer DEFAULT 0,
	"upsells_converted" integer DEFAULT 0,
	"upsell_revenue" real DEFAULT 0,
	"pro_accepted" boolean,
	"pro_feedback" text,
	"status" text DEFAULT 'generated' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "promo_code_usage" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"promo_code_id" varchar NOT NULL,
	"user_id" varchar NOT NULL,
	"service_request_id" varchar,
	"discount_applied" real NOT NULL,
	"used_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "promo_codes" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"code" text NOT NULL,
	"description" text,
	"discount_type" text NOT NULL,
	"discount_amount" real NOT NULL,
	"min_order_amount" real DEFAULT 0,
	"max_uses" integer,
	"current_uses" integer DEFAULT 0,
	"app_only" boolean DEFAULT false,
	"first_time_only" boolean DEFAULT false,
	"valid_from" text,
	"valid_until" text,
	"is_active" boolean DEFAULT true,
	"created_at" text NOT NULL,
	CONSTRAINT "promo_codes_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "promotions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"promotion_type" text NOT NULL,
	"discount_amount" real NOT NULL,
	"service_request_id" varchar,
	"applied_at" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "properties" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"address_hash" varchar,
	"full_address" text,
	"owner_id" varchar,
	"maintenance_score" integer DEFAULT 0,
	"last_assessment_date" text,
	"estimated_value_increase" integer DEFAULT 0,
	"unit" text,
	"city" text,
	"state" text,
	"zip_code" text,
	"county" text,
	"latitude" real,
	"longitude" real,
	"property_type" text DEFAULT 'single_family',
	"year_built" integer,
	"sqft" integer,
	"lot_size_sqft" integer,
	"bedrooms" integer,
	"bathrooms" real,
	"stories" integer,
	"garage_type" text,
	"has_pool" boolean DEFAULT false,
	"pool_type" text,
	"roof_type" text,
	"roof_age_years" integer,
	"exterior_type" text,
	"hvac_type" text,
	"hvac_age_years" integer,
	"property_health_score" real,
	"health_score_updated_at" text,
	"health_score_history" jsonb,
	"health_score_roof" real,
	"health_score_hvac" real,
	"health_score_exterior" real,
	"health_score_interior" real,
	"health_score_landscape" real,
	"health_score_pool" real,
	"health_score_appliances" real,
	"health_score_maintenance" real,
	"initial_scan_id" varchar,
	"last_scan_id" varchar,
	"total_scans" integer DEFAULT 0,
	"total_jobs_completed" integer DEFAULT 0,
	"total_spent" real DEFAULT 0,
	"last_service_date" text,
	"active_warranty_count" integer DEFAULT 0,
	"expiring_warranty_count" integer DEFAULT 0,
	"source" text DEFAULT 'organic',
	"builder_partnership_id" varchar,
	"realtor_referral_code" varchar,
	"move_in_date" text,
	"is_primary_residence" boolean DEFAULT true,
	"status" text DEFAULT 'active',
	"onboarding_completed" boolean DEFAULT false,
	"onboarding_completed_at" text,
	"onboarding_step" integer DEFAULT 0,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now(),
	CONSTRAINT "properties_address_hash_unique" UNIQUE("address_hash")
);
--> statement-breakpoint
CREATE TABLE "property_appliances" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" varchar NOT NULL,
	"category" text NOT NULL,
	"brand" text,
	"model_number" text,
	"serial_number" text,
	"install_date" text,
	"purchase_date" text,
	"purchase_price" real,
	"location" text,
	"capacity" text,
	"energy_rating" text,
	"specifications" jsonb,
	"estimated_lifespan_years" integer,
	"age_years" integer,
	"condition_score" real,
	"last_service_date" text,
	"next_service_due" text,
	"service_history" jsonb,
	"warranty_id" varchar,
	"under_insurance" boolean DEFAULT false,
	"insurance_policy_id" varchar,
	"manual_url" text,
	"receipt_url" text,
	"photo_urls" text[],
	"has_active_warranty" boolean DEFAULT false,
	"warranty_expires_at" text,
	"maintenance_alert_enabled" boolean DEFAULT true,
	"status" text DEFAULT 'active',
	"replaced_by" varchar,
	"notes" text,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "property_documents" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" varchar NOT NULL,
	"document_name" text NOT NULL,
	"document_type" text NOT NULL,
	"description" text,
	"file_url" text NOT NULL,
	"file_size" integer,
	"file_type" text,
	"thumbnail_url" text,
	"category" text,
	"tags" text[],
	"appliance_id" varchar,
	"warranty_id" varchar,
	"insurance_policy_id" varchar,
	"service_request_id" varchar,
	"document_date" text,
	"expiration_date" text,
	"issuer" text,
	"is_public" boolean DEFAULT false,
	"shared_with" text[],
	"ocr_text" text,
	"ai_summary" text,
	"ai_extracted_data" jsonb,
	"version" integer DEFAULT 1,
	"previous_version_id" varchar,
	"uploaded_by" varchar,
	"upload_source" text,
	"status" text DEFAULT 'active',
	"notes" text,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "property_events" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" varchar NOT NULL,
	"service_request_id" varchar,
	"event_type" varchar,
	"description" text,
	"verified_by" varchar,
	"photos_before" text,
	"photos_after" text,
	"date" text,
	"is_transferable" boolean DEFAULT true
);
--> statement-breakpoint
CREATE TABLE "property_health_events" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" varchar NOT NULL,
	"event_type" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"service_request_id" varchar,
	"appliance_id" varchar,
	"warranty_id" varchar,
	"insurance_policy_id" varchar,
	"dwellscan_id" varchar,
	"health_score_impact" real,
	"category_impacted" text,
	"previous_score" real,
	"new_score" real,
	"cost_amount" real,
	"value_saved" real,
	"preventive_value" real,
	"photo_urls" text[],
	"document_urls" text[],
	"receipt_url" text,
	"performed_by" text,
	"verified_by" text,
	"is_verified" boolean DEFAULT false,
	"verified_at" text,
	"event_date" text NOT NULL,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now(),
	"tags" text[],
	"is_public" boolean DEFAULT true,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "property_insurance" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" varchar NOT NULL,
	"insurance_type" text NOT NULL,
	"carrier" text NOT NULL,
	"policy_number" text NOT NULL,
	"agent_name" text,
	"agent_phone" text,
	"agent_email" text,
	"coverage_amount" real NOT NULL,
	"deductible" real,
	"annual_premium" real,
	"monthly_premium" real,
	"dwelling_coverage" real,
	"personal_property_coverage" real,
	"liability_coverage" real,
	"additional_coverages" text[],
	"effective_date" text NOT NULL,
	"expiration_date" text NOT NULL,
	"renewal_date" text,
	"discounts" jsonb,
	"total_discount_pct" real DEFAULT 0,
	"total_claims_made" integer DEFAULT 0,
	"last_claim_date" text,
	"claims_history" jsonb,
	"insurance_partner_id" varchar,
	"discount_eligible" boolean DEFAULT false,
	"renewal_alert_sent" boolean DEFAULT false,
	"renewal_alert_sent_at" text,
	"policy_document_url" text,
	"document_urls" text[],
	"status" text DEFAULT 'active',
	"notes" text,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "property_maintenance_schedule" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" varchar NOT NULL,
	"task_name" text NOT NULL,
	"task_description" text,
	"task_category" text,
	"service_type" text,
	"frequency" text NOT NULL,
	"frequency_days" integer,
	"next_due_date" text NOT NULL,
	"last_completed_date" text,
	"priority" text DEFAULT 'medium',
	"is_overdue" boolean DEFAULT false,
	"overdue_by" integer,
	"ai_generated" boolean DEFAULT false,
	"ai_confidence" real,
	"generated_from" text,
	"estimated_cost" real,
	"estimated_duration_hours" real,
	"total_completions" integer DEFAULT 0,
	"average_cost" real,
	"last_service_request_id" varchar,
	"reminder_enabled" boolean DEFAULT true,
	"reminder_days_before" integer DEFAULT 7,
	"last_reminder_sent" text,
	"appliance_id" varchar,
	"warranty_id" varchar,
	"status" text DEFAULT 'active',
	"notes" text,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "property_scores" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" varchar,
	"user_id" varchar NOT NULL,
	"total_score" integer DEFAULT 500,
	"maintenance_health" integer DEFAULT 50,
	"documentation_health" integer DEFAULT 50,
	"safety_health" integer DEFAULT 50,
	"last_updated" text DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "property_transfers" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" varchar,
	"from_user_id" varchar,
	"to_email" text NOT NULL,
	"claim_token" varchar NOT NULL,
	"status" varchar DEFAULT 'pending',
	"claimed_by_user_id" varchar,
	"created_at" text DEFAULT now(),
	"claimed_at" text,
	CONSTRAINT "property_transfers_claim_token_unique" UNIQUE("claim_token")
);
--> statement-breakpoint
CREATE TABLE "property_warranties" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" varchar NOT NULL,
	"warranty_type" text NOT NULL,
	"provider" text NOT NULL,
	"policy_number" text,
	"description" text,
	"coverage_items" text[],
	"coverage_amount" real,
	"deductible" real,
	"exclusions" text[],
	"start_date" text NOT NULL,
	"end_date" text NOT NULL,
	"duration_years" integer,
	"auto_renew" boolean DEFAULT false,
	"alert_90_day_sent" boolean DEFAULT false,
	"alert_90_day_sent_at" text,
	"alert_60_day_sent" boolean DEFAULT false,
	"alert_60_day_sent_at" text,
	"alert_30_day_sent" boolean DEFAULT false,
	"alert_30_day_sent_at" text,
	"expiration_alert_sent" boolean DEFAULT false,
	"provider_phone" text,
	"provider_email" text,
	"provider_website" text,
	"claim_instructions" text,
	"total_claims_made" integer DEFAULT 0,
	"last_claim_date" text,
	"document_urls" text[],
	"policy_document_url" text,
	"annual_cost" real,
	"total_cost_paid" real DEFAULT 0,
	"status" text DEFAULT 'active',
	"notes" text,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "pycker_online_status" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"pycker_id" varchar NOT NULL,
	"user_id" varchar NOT NULL,
	"latitude" real NOT NULL,
	"longitude" real NOT NULL,
	"accuracy" real,
	"status" text DEFAULT 'available' NOT NULL,
	"current_job_id" varchar,
	"last_updated" text NOT NULL,
	"location_consent_given" boolean DEFAULT false,
	"consent_given_at" text,
	"update_interval_seconds" integer DEFAULT 30,
	"expires_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pycker_vehicles" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"hauler_profile_id" varchar NOT NULL,
	"vehicle_type" text NOT NULL,
	"vehicle_name" text NOT NULL,
	"year" text,
	"make" text,
	"model" text,
	"license_plate" text,
	"capacity" text NOT NULL,
	"is_enclosed" boolean DEFAULT false,
	"has_trailer" boolean DEFAULT false,
	"trailer_size" text,
	"bed_length" text,
	"max_weight" integer,
	"description" text,
	"is_active" boolean DEFAULT true,
	"created_at" text NOT NULL,
	"photo_urls" text[] DEFAULT ARRAY[]::text[]
);
--> statement-breakpoint
CREATE TABLE "rebate_claims" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"hauler_id" varchar NOT NULL,
	"status" text DEFAULT 'pending',
	"receipt_url" text NOT NULL,
	"facility_id" varchar,
	"facility_name" text NOT NULL,
	"facility_address" text,
	"facility_type" text,
	"facility_approved" boolean DEFAULT false,
	"receipt_number" text,
	"receipt_date" text NOT NULL,
	"receipt_weight" real NOT NULL,
	"fee_charged" real,
	"job_completed_at" text,
	"estimated_weight" real,
	"job_total_price" real,
	"variance_percent" real,
	"within_variance" boolean DEFAULT false,
	"within_48_hours" boolean DEFAULT false,
	"validation_flags" text[],
	"rebate_amount" real,
	"ai_validation_status" text DEFAULT 'pending',
	"ai_validation_result" text,
	"ai_validation_notes" text,
	"ai_validated_at" text,
	"ai_confidence_score" real,
	"reviewed_by" varchar,
	"reviewed_at" text,
	"denial_reason" text,
	"submitted_at" text NOT NULL,
	"paid_out" boolean DEFAULT false,
	"paid_out_at" text
);
--> statement-breakpoint
CREATE TABLE "recurring_jobs" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"business_account_id" varchar NOT NULL,
	"service_type" text NOT NULL,
	"pickup_address" text NOT NULL,
	"pickup_city" text NOT NULL,
	"pickup_zip" text NOT NULL,
	"description" text,
	"frequency" text NOT NULL,
	"preferred_day_of_week" integer,
	"preferred_time_slot" text,
	"estimated_load_size" text NOT NULL,
	"negotiated_price" real,
	"is_active" boolean DEFAULT true,
	"next_scheduled_date" text,
	"last_completed_date" text,
	"preferred_hauler_id" varchar,
	"total_completed_jobs" integer DEFAULT 0,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "recurring_subscriptions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar NOT NULL,
	"service_type" text NOT NULL,
	"frequency" text NOT NULL,
	"home_details" jsonb NOT NULL,
	"preferred_day" text,
	"preferred_time_window" text,
	"assigned_pro_id" varchar,
	"stripe_subscription_id" text,
	"status" text DEFAULT 'active' NOT NULL,
	"next_booking_date" text,
	"bookings_completed" integer DEFAULT 0,
	"minimum_bookings_commitment" integer DEFAULT 3,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now() NOT NULL,
	"cancelled_at" text,
	"cancellation_reason" text
);
--> statement-breakpoint
CREATE TABLE "referral_partners" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"business_name" varchar NOT NULL,
	"category" varchar NOT NULL,
	"contact_name" varchar,
	"email" varchar NOT NULL,
	"phone" varchar,
	"website" text,
	"service_area" text,
	"commission_rate" integer DEFAULT 10,
	"is_active" boolean DEFAULT true,
	"rating" real,
	"jobs_completed" integer DEFAULT 0,
	"created_at" text DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "referrals" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"referrer_id" varchar NOT NULL,
	"referred_email" text NOT NULL,
	"referred_user_id" varchar,
	"referral_code" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"referrer_bonus_amount" real DEFAULT 50 NOT NULL,
	"referred_bonus_amount" real DEFAULT 50 NOT NULL,
	"referrer_paid_at" text,
	"referred_paid_at" text,
	"first_job_completed_at" text,
	"created_at" text NOT NULL,
	"expires_at" text,
	CONSTRAINT "referrals_referral_code_unique" UNIQUE("referral_code")
);
--> statement-breakpoint
CREATE TABLE "score_history" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"score_id" varchar NOT NULL,
	"service_request_id" varchar,
	"points_changed" integer,
	"reason" text,
	"category" varchar,
	"created_at" text DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "seasonal_advisories" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" varchar NOT NULL,
	"user_id" varchar NOT NULL,
	"zip_code" text,
	"trigger_type" text NOT NULL,
	"trigger_data" jsonb,
	"title" text NOT NULL,
	"message" text NOT NULL,
	"urgency" text DEFAULT 'medium' NOT NULL,
	"category" text,
	"recommended_services" jsonb,
	"bundle_offer" jsonb,
	"estimated_savings" real,
	"property_health_score_at_time" real,
	"relevant_appliance_data" jsonb,
	"last_service_dates" jsonb,
	"delivery_channel" text DEFAULT 'push',
	"delivered_at" text,
	"opened_at" text,
	"clicked_at" text,
	"dismissed_at" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"resulted_in_booking" boolean DEFAULT false,
	"booking_service_request_ids" text[],
	"booking_total_value" real,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"expires_at" text
);
--> statement-breakpoint
CREATE TABLE "sentiment_flags" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"source_type" text NOT NULL,
	"source_id" varchar,
	"service_request_id" varchar,
	"customer_id" varchar,
	"hauler_id" varchar,
	"raw_text" text NOT NULL,
	"sentiment_score" real NOT NULL,
	"risk_level" text DEFAULT 'low' NOT NULL,
	"key_phrases" text[],
	"issues" text[],
	"recommended_action" text NOT NULL,
	"urgency_reason" text,
	"status" text DEFAULT 'new',
	"resolved_by" varchar,
	"resolved_at" text,
	"resolution_notes" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "service_contracts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"customer_id" varchar NOT NULL,
	"hauler_id" varchar NOT NULL,
	"scope_of_work" text NOT NULL,
	"agreed_price" real NOT NULL,
	"customer_signature" text,
	"customer_signed_at" text,
	"pro_signature" text,
	"pro_signed_at" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "service_esg_metrics" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"service_request_id" varchar NOT NULL,
	"service_type" text NOT NULL,
	"water_used_gallons" real DEFAULT 0,
	"water_saved_gallons" real DEFAULT 0,
	"water_efficiency_pct" real DEFAULT 0,
	"energy_used_kwh" real DEFAULT 0,
	"energy_saved_kwh" real DEFAULT 0,
	"chemical_used_oz" real DEFAULT 0,
	"chemical_type" text,
	"chemical_co2e_per_oz" real DEFAULT 0,
	"materials_salvaged_lbs" real DEFAULT 0,
	"salvage_rate" real DEFAULT 0,
	"prevention_value" real DEFAULT 0,
	"repair_vs_replace_savings" real DEFAULT 0,
	"route_optimization_savings" real DEFAULT 0,
	"carbon_sequestered" real DEFAULT 0,
	"total_co2_saved_lbs" real DEFAULT 0,
	"total_co2_emitted_lbs" real DEFAULT 0,
	"net_co2_impact_lbs" real DEFAULT 0,
	"esg_score" real DEFAULT 0,
	"calculation_method" text NOT NULL,
	"verification_status" text DEFAULT 'pending',
	"calculation_details" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "service_requests" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar NOT NULL,
	"service_type" text NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"pickup_address" text NOT NULL,
	"pickup_city" text NOT NULL,
	"pickup_zip" text NOT NULL,
	"pickup_lat" real,
	"pickup_lng" real,
	"destination_address" text,
	"destination_city" text,
	"destination_zip" text,
	"destination_lat" real,
	"destination_lng" real,
	"pickup_stairs" integer DEFAULT 0,
	"destination_stairs" integer DEFAULT 0,
	"move_service_mode" text DEFAULT 'truck_and_mover',
	"load_estimate" text NOT NULL,
	"description" text,
	"access_notes" text,
	"scheduled_for" text NOT NULL,
	"price_estimate" real,
	"final_price" real,
	"live_price" real,
	"base_service_price" real,
	"surge_factor" real DEFAULT 1,
	"distance_miles" real,
	"assigned_hauler_id" varchar,
	"photo_urls" text[],
	"started_at" text,
	"completed_at" text,
	"created_at" text NOT NULL,
	"stripe_payment_intent_id" text,
	"payment_status" text DEFAULT 'pending',
	"platform_fee" real,
	"hauler_payout" real,
	"paid_at" text,
	"accepted_at" text,
	"contact_required_by" text,
	"contact_confirmed_at" text,
	"contact_released_at" text,
	"hauler_penalty_applied" boolean DEFAULT false,
	"tip_amount" real,
	"tip_paid_at" text,
	"tip_stripe_transfer_id" text,
	"booking_source" text DEFAULT 'app',
	"first_job_discount_applied" boolean DEFAULT false,
	"promotion_discount_amount" real DEFAULT 0,
	"prefer_verified_pro" boolean DEFAULT false,
	"cancelled_at" text,
	"cancelled_by" text,
	"cancellation_reason" text,
	"cancellation_penalty_charged" boolean DEFAULT false,
	"cancellation_penalty_id" varchar,
	"environmental_certificate_id" varchar,
	"disposal_recycled_percent" integer DEFAULT 0,
	"disposal_donated_percent" integer DEFAULT 0,
	"disposal_landfilled_percent" integer DEFAULT 0,
	"carbon_footprint_lbs" real,
	"carbon_offset_purchased" boolean DEFAULT false,
	"disposal_facilities" text[],
	"environmental_report_generated_at" text,
	"truck_size" text,
	"bedroom_count" integer,
	"has_appliances" boolean DEFAULT false,
	"appliances_list" text[],
	"has_heavy_items" boolean DEFAULT false,
	"heavy_items_list" text[],
	"estimated_hours" real,
	"preferred_language" text DEFAULT 'en',
	"matching_started_at" text,
	"matching_expires_at" text,
	"needs_manual_match" boolean DEFAULT false,
	"manual_match_alert_sent_at" text,
	"customer_phone" text,
	"customer_email" text,
	"bnpl_enabled" boolean DEFAULT false,
	"bnpl_provider" text,
	"bnpl_payment_method_id" text,
	"backup_payment_method_id" text,
	"bnpl_confirmed_at" text,
	"bnpl_adjustment_charged" real,
	"bnpl_adjustment_charged_at" text,
	"customer_items" text,
	"ai_price_min" real,
	"ai_price_max" real,
	"ai_confidence" real,
	"verification_status" text DEFAULT 'pending',
	"verified_at" text,
	"verifier_notes" text,
	"verified_items" text,
	"route_order" integer,
	"bounty_amount" integer DEFAULT 0,
	"last_bounty_update" text,
	"access_type" text DEFAULT 'person',
	"encrypted_access_code" text,
	"access_window_start" text,
	"access_window_end" text,
	"carbon_offset_opt_in" boolean DEFAULT false,
	"carbon_offset_fee" integer DEFAULT 0,
	"ai_estimated_weight" integer,
	"actual_disposal_weight" integer,
	"ai_price_quote" integer,
	"final_disposal_cost" integer,
	"vision_accuracy_score" integer,
	"training_consent" boolean DEFAULT true,
	"original_ai_price" integer,
	"final_locked_price" integer,
	"adjustment_reason" text,
	"added_line_items" text,
	"customer_signature_url" text,
	"is_price_locked" boolean DEFAULT false,
	"arrived_at" text,
	"is_ghost_flagged" boolean DEFAULT false,
	"insurance_provider" text DEFAULT 'UpTend_Blanket',
	"external_policy_id" text,
	"insurance_cost" integer,
	"is_agent_booking" boolean DEFAULT false,
	"square_footage" integer,
	"story_count" integer,
	"labor_hours" integer,
	"labor_crew_size" integer DEFAULT 1,
	"demo_debris_type" varchar,
	"is_consultation_credit_applied" boolean DEFAULT false,
	"price_verified" boolean DEFAULT false,
	"verified_price" real,
	"price_adjustment" real,
	"price_verification_data" text,
	"verification_photos" text[],
	"price_approval_pending" boolean DEFAULT false,
	"price_approval_requested_at" text,
	"price_approval_responded_at" text,
	"customer_approved_price_adjustment" boolean,
	"customer_notes" text,
	"discounts_applied" text,
	"dwellscan_credit_used" real,
	"dwellscan_credit_id" varchar,
	"multi_service_discount_percent" real,
	"pm_tier_discount_percent" real,
	"promo_code_used" varchar,
	"promo_code_discount_amount" real,
	"total_discount_amount" real,
	"price_before_discounts" real,
	"quote_method" varchar DEFAULT 'manual',
	"estimated_price" real,
	"fresh_space_details" jsonb,
	"recurring_subscription_id" varchar
);
--> statement-breakpoint
CREATE TABLE "service_subscriptions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar NOT NULL,
	"service_type" text NOT NULL,
	"frequency" text NOT NULL,
	"preferred_day" text,
	"preferred_time" text,
	"address_line1" text,
	"address_line2" text,
	"city" text,
	"state" text,
	"zip" text,
	"notes" text,
	"stripe_subscription_id" text,
	"status" text DEFAULT 'active' NOT NULL,
	"next_service_date" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "smart_schedule_suggestions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"property_id" varchar,
	"service_types" text[] NOT NULL,
	"suggested_slots" jsonb,
	"scheduling_reason" text,
	"weather_forecast" jsonb,
	"customer_patterns" jsonb,
	"pro_availability" jsonb,
	"service_order_logic" text,
	"status" text DEFAULT 'suggested' NOT NULL,
	"accepted_at" text,
	"modified_schedule" jsonb,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sms_conversations" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"phone_number" text NOT NULL,
	"user_id" varchar,
	"language" text DEFAULT 'en',
	"last_message_at" text DEFAULT now() NOT NULL,
	"message_count" integer DEFAULT 0,
	"is_active" boolean DEFAULT true,
	"messages_last_hour" integer DEFAULT 0,
	"last_hour_reset_at" text DEFAULT now(),
	"is_rate_limited" boolean DEFAULT false,
	"rate_limited_until" text,
	"opted_out" boolean DEFAULT false,
	"opted_out_at" text,
	"opt_out_reason" text,
	"customer_name" text,
	"customer_email" text,
	"callback_requested" boolean DEFAULT false,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now(),
	CONSTRAINT "sms_conversations_phone_number_unique" UNIQUE("phone_number")
);
--> statement-breakpoint
CREATE TABLE "sms_messages" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"conversation_id" varchar NOT NULL,
	"direction" text NOT NULL,
	"message_body" text NOT NULL,
	"twilio_message_sid" text,
	"media_urls" text[],
	"media_content_types" text[],
	"ai_analysis_result" jsonb,
	"quote_generated" boolean DEFAULT false,
	"quoted_price" real,
	"delivery_status" text,
	"error_code" text,
	"error_message" text,
	"sent_at" text DEFAULT now(),
	"delivered_at" text,
	"created_at" text DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "surge_modifiers" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"day_of_week" integer,
	"start_hour" integer NOT NULL,
	"end_hour" integer NOT NULL,
	"multiplier" real DEFAULT 1 NOT NULL,
	"reason" text,
	"is_active" boolean DEFAULT true
);
--> statement-breakpoint
CREATE TABLE "tax_credit_claims" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"business_account_id" varchar NOT NULL,
	"tax_year" integer NOT NULL,
	"total_diverted_lbs" real DEFAULT 0,
	"total_recycled_lbs" real DEFAULT 0,
	"total_donated_lbs" real DEFAULT 0,
	"estimated_credit_amount" real DEFAULT 0,
	"job_count" integer DEFAULT 0,
	"report_url" text,
	"status" text DEFAULT 'draft',
	"generated_at" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "violation_communications" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"violation_id" varchar,
	"property_id" varchar,
	"business_account_id" varchar,
	"communication_type" text,
	"method" text,
	"sent_by" varchar,
	"channel" text NOT NULL,
	"recipient" text NOT NULL,
	"subject" text,
	"message" text NOT NULL,
	"sent_at" text DEFAULT now() NOT NULL,
	"created_at" text DEFAULT now(),
	"opened" boolean DEFAULT false,
	"opened_at" text,
	"clicked" boolean DEFAULT false,
	"clicked_at" text,
	"replied" boolean DEFAULT false,
	"replied_at" text,
	"bounced" boolean DEFAULT false,
	"unsubscribed" boolean DEFAULT false,
	"status" text DEFAULT 'sent'
);
--> statement-breakpoint
CREATE TABLE "voice_booking_sessions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"caller_phone" text NOT NULL,
	"user_id" varchar,
	"property_id" varchar,
	"call_direction" text DEFAULT 'inbound' NOT NULL,
	"call_duration_seconds" integer,
	"call_started_at" text NOT NULL,
	"call_ended_at" text,
	"transcript_url" text,
	"transcript_text" text,
	"detected_language" text DEFAULT 'en',
	"detected_intent" text,
	"detected_service" text,
	"stt_provider" text,
	"tts_provider" text,
	"ai_model_used" text,
	"status" text DEFAULT 'in_progress' NOT NULL,
	"outcome" text,
	"service_request_id" varchar,
	"quoted_price" real,
	"scheduled_date" text,
	"escalated_to_human" boolean DEFAULT false,
	"escalation_reason" text,
	"human_agent_id" varchar,
	"customer_satisfaction" integer,
	"created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "worker_skills" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"hauler_profile_id" varchar NOT NULL,
	"skill_type" text NOT NULL,
	"rating" real DEFAULT 5,
	"jobs_completed" integer DEFAULT 0,
	"last_used_at" text,
	"verified_by_admin" boolean DEFAULT false,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "customer_addresses" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"label" text NOT NULL,
	"street" text NOT NULL,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"zip_code" text NOT NULL,
	"lat" real,
	"lng" real,
	"is_default" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"sid" varchar PRIMARY KEY NOT NULL,
	"sess" jsonb NOT NULL,
	"expire" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"username" text,
	"password" text,
	"email" varchar,
	"first_name" varchar,
	"last_name" varchar,
	"profile_image_url" varchar,
	"role" text DEFAULT 'customer' NOT NULL,
	"phone" text,
	"current_lat" real,
	"current_lng" real,
	"last_location_update" text,
	"google_id" text,
	"stripe_customer_id" text,
	"total_jobs_completed" real DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "property_transfers" ADD CONSTRAINT "property_transfers_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "service_esg_metrics" ADD CONSTRAINT "service_esg_metrics_service_request_id_service_requests_id_fk" FOREIGN KEY ("service_request_id") REFERENCES "public"."service_requests"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "IDX_session_expire" ON "sessions" USING btree ("expire");