export interface CostGuide {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  serviceType: string;
  avgCostLow: number;
  avgCostHigh: number;
  costUnit: string;
  factors: string[];
  whatsIncluded: string[];
  tips: string[];
  description: string;
}

export const costGuides: CostGuide[] = [
  {
    slug: "junk-removal",
    title: "Junk Removal Cost in Orlando",
    metaTitle: "Junk Removal Cost Orlando 2026 | Pricing Guide | UpTend",
    metaDescription: "How much does junk removal cost in Orlando? Average $99–$549 for most jobs. See pricing factors, what's included, and book instantly with UpTend.",
    serviceType: "junk_removal",
    avgCostLow: 99,
    avgCostHigh: 549,
    costUnit: "per load",
    factors: [
      "Volume of items (measured in truck loads — ¼, ½, ¾, or full)",
      "Type of items — hazardous materials, appliances, and electronics may cost more",
      "Accessibility — stairs, narrow hallways, or long carry distances add labor time",
      "Location within Orlando metro — distance from disposal/recycling facilities",
      "Urgency — same-day pickup typically has a premium",
    ],
    whatsIncluded: [
      "All labor for loading and hauling",
      "Truck and fuel costs",
      "Responsible disposal, recycling, and donation sorting",
      "360° Home DNA Scan of the job",
      "Verified Impact Report showing where items went",
    ],
    tips: [
      "Consolidate items in one area before the crew arrives to save time",
      "Separate recyclables and donations — some may reduce your cost",
      "Book mid-week for better availability and sometimes lower rates",
      "Take photos of items beforehand for a more accurate instant quote",
    ],
    description: "Orlando junk removal costs depend primarily on volume. A quarter-truck load starts around $99, while a full truck runs $450–$549. UpTend pros handle everything from old furniture and appliances to yard debris and construction waste, with verified eco-friendly disposal.",
  },
  {
    slug: "pressure-washing",
    title: "Pressure Washing Cost in Orlando",
    metaTitle: "Pressure Washing Cost Orlando 2026 | Pricing Guide | UpTend",
    metaDescription: "Pressure washing in Orlando costs $150–$500 on average. See what affects pricing, what's included, and book with licensed UpTend pros.",
    serviceType: "pressure_washing",
    avgCostLow: 150,
    avgCostHigh: 500,
    costUnit: "per project",
    factors: [
      "Square footage of the area being cleaned",
      "Surface type — concrete, pavers, vinyl siding, brick, or wood",
      "Severity of stains, mold, or mildew buildup",
      "Height and accessibility (multi-story homes cost more)",
      "Additional treatments — sealing, soft washing for delicate surfaces",
    ],
    whatsIncluded: [
      "Professional-grade pressure washing equipment",
      "Eco-friendly cleaning solutions",
      "Driveway, walkway, patio, or home exterior cleaning",
      "Pre-treatment for tough stains and mold",
      "All labor and cleanup",
    ],
    tips: [
      "Orlando's humidity means mold builds fast — schedule every 6–12 months",
      "Bundle driveway + house exterior for a better rate",
      "Soft washing is safer for painted surfaces and roofs",
      "Best done before painting or selling your home for maximum curb appeal",
    ],
    description: "In Orlando's humid climate, pressure washing is essential maintenance. Most homeowners pay $150–$500 depending on the scope. Driveways average $100–$200, while a full home exterior runs $250–$500.",
  },
  {
    slug: "gutter-cleaning",
    title: "Gutter Cleaning Cost in Orlando",
    metaTitle: "Gutter Cleaning Cost Orlando 2026 | Pricing Guide | UpTend",
    metaDescription: "Gutter cleaning in Orlando costs $75–$250 for most homes. Learn pricing factors and book trusted UpTend pros.",
    serviceType: "gutter_cleaning",
    avgCostLow: 75,
    avgCostHigh: 250,
    costUnit: "per service",
    factors: [
      "Linear feet of gutters",
      "Home height — single vs. multi-story",
      "Level of debris buildup (leaves, pine needles, roof granules)",
      "Gutter guard removal/reinstallation if applicable",
      "Downspout unclogging needs",
    ],
    whatsIncluded: [
      "Full gutter and downspout cleaning",
      "Debris removal and bagging",
      "Gutter flow testing with water flush",
      "Visual inspection for damage or sagging",
      "Ground-level cleanup",
    ],
    tips: [
      "Clean gutters twice a year in Orlando — before and after hurricane season",
      "Oak trees and palms shed heavily; nearby trees mean more frequent cleaning",
      "Clogged gutters can cause foundation damage — don't skip this maintenance",
      "Ask about gutter guard installation to reduce future cleaning frequency",
    ],
    description: "Orlando homeowners typically pay $75–$250 for professional gutter cleaning. Single-story ranch homes are on the lower end, while large two-story homes with lots of tree coverage cost more.",
  },
  {
    slug: "moving-labor",
    title: "Moving Labor Cost in Orlando",
    metaTitle: "Moving Labor Cost Orlando 2026 | Pricing Guide | UpTend",
    metaDescription: "Moving labor in Orlando costs $80–$150/hour for a 2-person crew. See full pricing breakdown and book with UpTend.",
    serviceType: "moving_labor",
    avgCostLow: 80,
    avgCostHigh: 150,
    costUnit: "per hour (2-person crew)",
    factors: [
      "Number of movers needed (2–4 person crews)",
      "Duration of the move — most take 2–6 hours",
      "Stairs, elevators, or long-carry distances",
      "Heavy or specialty items (pianos, safes, pool tables)",
      "Whether you need truck + movers or labor-only",
    ],
    whatsIncluded: [
      "Professional moving crew (2+ movers)",
      "Furniture disassembly and reassembly as needed",
      "Furniture blankets and basic protection",
      "Loading and unloading assistance",
      "Careful handling of fragile items",
    ],
    tips: [
      "Pack and label boxes beforehand to minimize hourly costs",
      "Disassemble furniture yourself if possible to save crew time",
      "Book labor-only if you already have a rental truck",
      "Move mid-month or mid-week for better rates and availability",
    ],
    description: "Orlando moving labor typically runs $80–$150/hour for a two-person crew. Most apartment moves take 2–4 hours ($160–$600), while house moves can run 4–8 hours ($320–$1,200). Labor-only rates are lower than full-service moves.",
  },
  {
    slug: "handyman",
    title: "Handyman Service Cost in Orlando",
    metaTitle: "Handyman Cost Orlando 2026 | Pricing Guide | UpTend",
    metaDescription: "Handyman services in Orlando cost $75–$125/hour. See common project costs and book trusted UpTend handyman pros.",
    serviceType: "handyman",
    avgCostLow: 75,
    avgCostHigh: 125,
    costUnit: "per hour",
    factors: [
      "Type of work — simple repairs vs. skilled installations",
      "Materials needed (often billed separately)",
      "Number of tasks — bundling multiple small jobs saves money",
      "Accessibility and complexity of the repair",
      "Permit requirements for electrical or plumbing work",
    ],
    whatsIncluded: [
      "Skilled labor for repairs and installations",
      "Basic tools and equipment",
      "TV mounting, shelf installation, fixture replacement",
      "Minor plumbing and electrical repairs",
      "Furniture assembly and door/lock repairs",
    ],
    tips: [
      "Make a list of all small repairs and bundle them into one visit",
      "Some tasks require a licensed specialist — ask if unsure",
      "Provide materials yourself to save on markup",
      "Take photos of the issue before booking for faster quoting",
    ],
    description: "Orlando handyman rates average $75–$125/hour. Common projects: TV mounting ($75–$150), ceiling fan install ($100–$200), door repair ($75–$175), faucet replacement ($100–$250). Bundling multiple tasks in one visit is the most cost-effective approach.",
  },
  {
    slug: "demolition",
    title: "Light Demolition Cost in Orlando",
    metaTitle: "Demolition Cost Orlando 2026 | Pricing Guide | UpTend",
    metaDescription: "Light demolition in Orlando costs $200–$1,500+. Learn what affects demo pricing and book with UpTend.",
    serviceType: "light_demolition",
    avgCostLow: 200,
    avgCostHigh: 1500,
    costUnit: "per project",
    factors: [
      "Scope — single room vs. multi-room demo",
      "Materials being demolished (drywall, tile, concrete, cabinets)",
      "Debris hauling and disposal requirements",
      "Presence of hazardous materials (asbestos, lead paint) requiring special handling",
      "Structural considerations and permit needs",
    ],
    whatsIncluded: [
      "Demolition labor and basic equipment",
      "Debris removal and hauling to proper disposal",
      "Floor protection and dust containment",
      "Cabinet, countertop, or fixture removal",
      "Post-demo broom-clean sweep",
    ],
    tips: [
      "Get a clear scope in writing before work begins",
      "Check if permits are needed for structural demolition in Orange County",
      "Salvageable materials (cabinets, fixtures) can be donated to reduce disposal costs",
      "Schedule demo before your contractor needs the space ready",
    ],
    description: "Light demolition in Orlando ranges from $200 for a small bathroom gut to $1,500+ for larger kitchen or multi-room demos. Costs depend heavily on materials, scope, and disposal needs. UpTend includes debris hauling in most demo quotes.",
  },
  {
    slug: "garage-cleanout",
    title: "Garage Cleanout Cost in Orlando",
    metaTitle: "Garage Cleanout Cost Orlando 2026 | Pricing Guide | UpTend",
    metaDescription: "Garage cleanout in Orlando costs $299–$500. See what's included and book with UpTend pros.",
    serviceType: "garage_cleanout",
    avgCostLow: 150,
    avgCostHigh: 999,
    costUnit: "per cleanout",
    factors: [
      "Garage size (1-car, 2-car, 3-car)",
      "Volume and weight of items to remove",
      "Hazardous items (paint, chemicals, oil) requiring special disposal",
      "Organization services vs. full cleanout",
      "Whether items need sorting for donation, recycling, or disposal",
    ],
    whatsIncluded: [
      "Full garage emptying and debris removal",
      "Sorting items for donation, recycling, and disposal",
      "Loading and hauling all unwanted items",
      "Sweep and basic cleaning after removal",
      "Verified Impact Report on item destinations",
    ],
    tips: [
      "Pre-sort items you want to keep vs. remove to speed up the job",
      "Orlando humidity damages stored items fast — cleanout regularly",
      "Combine with pressure washing for a full garage refresh",
      "Good time to install shelving or storage systems afterward",
    ],
    description: "A full garage cleanout in Orlando typically costs $150–$500 depending on the amount of stuff. A lightly cluttered 2-car garage runs about $150–$250, while a packed-to-the-ceiling situation can reach $400–$500 including disposal.",
  },
  {
    slug: "home-cleaning",
    title: "Home Cleaning Cost in Orlando",
    metaTitle: "Home Cleaning Cost Orlando 2026 | Pricing Guide | UpTend",
    metaDescription: "Home cleaning in Orlando costs $100–$300 per visit. See pricing by home size and cleaning type with UpTend.",
    serviceType: "home_cleaning",
    avgCostLow: 100,
    avgCostHigh: 300,
    costUnit: "per visit",
    factors: [
      "Home size (square footage and number of bedrooms/bathrooms)",
      "Cleaning type — standard, deep clean, or move-in/move-out",
      "Frequency — one-time vs. recurring (weekly/biweekly discounts)",
      "Pet ownership (pet hair removal adds time)",
      "Special requests — inside oven, inside fridge, windows",
    ],
    whatsIncluded: [
      "Full kitchen cleaning (counters, appliances, sink, floors)",
      "Bathroom sanitization (toilet, shower, vanity, mirrors)",
      "Dusting all surfaces, ceiling fans, and baseboards",
      "Vacuuming and mopping all floors",
      "Tidying and making beds",
    ],
    tips: [
      "Recurring service (biweekly) is 15–20% cheaper per visit than one-time",
      "Deep cleans cost more but set a clean baseline for maintenance cleaning",
      "Declutter before the team arrives so they can focus on actual cleaning",
      "Move-out cleans help secure your security deposit — worth the investment",
    ],
    description: "Standard home cleaning in Orlando ranges from $100–$180 for a 2-bed/2-bath to $200–$300 for a 4-bed/3-bath. Deep cleaning costs 1.5–2x more. Recurring biweekly service averages $120–$200/visit with built-in discounts.",
  },
  {
    slug: "pool-cleaning",
    title: "Pool Cleaning Cost in Orlando",
    metaTitle: "Pool Cleaning Cost Orlando 2026 | Pricing Guide | UpTend",
    metaDescription: "Pool cleaning in Orlando costs $80–$200/month for regular service. See what's included and book with UpTend.",
    serviceType: "pool_cleaning",
    avgCostLow: 80,
    avgCostHigh: 200,
    costUnit: "per month",
    factors: [
      "Pool size and type (in-ground vs. above-ground)",
      "Frequency — weekly vs. biweekly service",
      "Chemical needs based on water chemistry",
      "Equipment condition (pump, filter, chlorinator)",
      "Whether pool has a screen enclosure (less debris = lower cost)",
    ],
    whatsIncluded: [
      "Skimming surface and emptying baskets",
      "Brushing walls and tile line",
      "Vacuuming pool floor",
      "Chemical testing and balancing",
      "Filter cleaning and equipment inspection",
    ],
    tips: [
      "Weekly service keeps chemicals balanced and prevents costly algae blooms",
      "Orlando's heat and rain mean pools need more frequent attention than up north",
      "A screen enclosure dramatically reduces debris and maintenance costs",
      "Ask about green pool recovery if your pool has turned — costs $200–$400 extra",
    ],
    description: "Regular pool cleaning in Orlando runs $80–$200/month for weekly service. Most standard residential pools (10,000–20,000 gallons) fall in the $100–$150/month range. One-time cleanings for neglected pools cost $200–$500 depending on condition.",
  },
  {
    slug: "landscaping",
    title: "Landscaping Cost in Orlando",
    metaTitle: "Landscaping Cost Orlando 2026 | Pricing Guide | UpTend",
    metaDescription: "Landscaping in Orlando costs $50–$300/visit for maintenance, $500–$5,000+ for design. See full pricing guide.",
    serviceType: "landscaping",
    avgCostLow: 50,
    avgCostHigh: 300,
    costUnit: "per visit (maintenance)",
    factors: [
      "Lot size and amount of turf/garden beds",
      "Service type — mowing/maintenance vs. design/installation",
      "Plant and material costs for new installations",
      "Irrigation system needs",
      "Frequency of service (weekly during growing season)",
    ],
    whatsIncluded: [
      "Lawn mowing, edging, and blowing",
      "Hedge and shrub trimming",
      "Weed removal from beds and walkways",
      "Seasonal flower planting (if requested)",
      "Basic yard debris cleanup",
    ],
    tips: [
      "Orlando lawns (St. Augustine) grow year-round — weekly mowing is standard",
      "Use Florida-native plants to reduce water and maintenance costs",
      "Bundle mowing with pressure washing for curb appeal maintenance packages",
      "Mulch beds 2x/year to reduce weeds and retain moisture in sandy soil",
    ],
    description: "UpTend Landscaping: One-time mow from $49 (≤¼ acre) or $79 (≤½ acre). Yard cleanup $149–$299. Recurring monthly plans: Mow & Go $99/mo (≤¼ acre) or $149/mo (≤½ acre) for weekly mow + blow + edging. Full Service $159/mo (≤¼ acre) or $219/mo (≤½ acre) adds trim, weed beds, and monthly hedge trim. Premium $249/mo (≤¼ acre) or $329/mo (≤½ acre) includes seasonal flowers, mulch 2x/year, and irrigation check.",
  },
  {
    slug: "carpet-cleaning",
    title: "Carpet Cleaning Cost in Orlando",
    metaTitle: "Carpet Cleaning Cost Orlando 2026 | Pricing Guide | UpTend",
    metaDescription: "Carpet cleaning in Orlando costs $50–$89 per room. See full tier pricing and book with UpTend.",
    serviceType: "carpet_cleaning",
    avgCostLow: 99,
    avgCostHigh: 300,
    costUnit: "per home",
    factors: [
      "Number of rooms and total square footage",
      "Cleaning tier — Standard ($50/room), Deep Clean ($75/room), or Pet Treatment ($89/room)",
      "Add-ons like Scotchgard protectant ($20/room)",
      "Hallways ($25 each) and stairs ($25/flight)",
      "Whole house packages available (3BR/2BA $149, 4-5BR $199)",
    ],
    whatsIncluded: [
      "Pre-treatment of stains and high-traffic areas",
      "Professional hot water extraction (steam) cleaning",
      "All rooms and hallways as booked",
      "Post-cleaning grooming for faster drying",
      "Eco-friendly, pet-safe cleaning solutions",
    ],
    tips: [
      "Vacuum thoroughly before the appointment for better results",
      "Move small items and breakables off the floor beforehand",
      "Professional cleaning every 12–18 months extends carpet life significantly",
      "Choose Pet Treatment ($89/room) if you have pets — standard cleaning won't fully eliminate odors",
      "Whole house packages (3BR $129, 4-5BR $215) save vs. per-room pricing",
    ],
    description: "UpTend Carpet Cleaning: Standard Steam Clean $50/room, Deep Clean $75/room, Pet Treatment $89/room. Hallways $25 each, stairs $25/flight. Scotchgard protectant $20/room add-on. Whole house packages: 3BR/2BA $129, 4-5BR $215. $100 minimum charge (covers up to 2 rooms standard).",
  },
];

export function getCostGuideBySlug(slug: string): CostGuide | undefined {
  return costGuides.find((g) => g.slug === slug);
}
