-- DIY Diagnosis Patterns Seed Data
-- 30+ patterns across 10 appliance categories

INSERT INTO diy_diagnosis_patterns (appliance_type, symptom_description, possible_causes, diagnostic_questions) VALUES

-- GARBAGE DISPOSAL (3)
('garbage_disposal', 'Garbage disposal won''t turn on', 
 '[{"cause":"Tripped reset button","difficulty":1,"steps":["Locate red reset button on bottom of unit","Press firmly until it clicks","Test the switch"],"tools":["Flashlight"],"parts":[],"safety":"Ensure switch is OFF before reaching under sink"},{"cause":"Tripped circuit breaker","difficulty":1,"steps":["Check electrical panel for tripped breaker","Reset the breaker","Test disposal"],"tools":[],"parts":[],"safety":"Do not touch panel with wet hands"},{"cause":"Faulty wall switch","difficulty":3,"steps":["Turn off breaker","Remove switch plate","Test with multimeter","Replace if no continuity"],"tools":["Screwdriver","Multimeter"],"parts":["Wall switch ~$3"],"safety":"MUST turn off breaker first. If uncomfortable with electrical, call a pro."}]',
 '[{"q":"Is there any humming sound when you flip the switch?","followup":{"yes":"Motor is jammed, not dead","no":"Electrical issue likely"}},{"q":"Have you checked the red reset button on the bottom of the unit?","followup":{"yes":"Did it click when pressed?","no":"Try that first — it''s the most common fix"}}]'),

('garbage_disposal', 'Garbage disposal is humming but not spinning',
 '[{"cause":"Jammed flywheel","difficulty":1,"steps":["Turn off disposal and power","Insert hex wrench into bottom center hole","Work back and forth to free jam","Remove debris with tongs (NEVER hands)","Reset and test"],"tools":["1/4 inch hex wrench (Allen key)","Tongs or pliers"],"parts":[],"safety":"NEVER put hands inside disposal. ALWAYS turn off power first."},{"cause":"Foreign object stuck","difficulty":1,"steps":["Turn off power at breaker","Use flashlight to look inside","Remove object with tongs or pliers","Test"],"tools":["Flashlight","Tongs"],"parts":[],"safety":"NEVER put hands inside the disposal chamber"}]',
 '[{"q":"Did you recently put anything unusual down the disposal (bones, glass, silverware)?","followup":{"yes":"Likely a foreign object jam","no":"Could be food buildup"}},{"q":"Can you see anything stuck inside with a flashlight?","followup":{"yes":"We''ll get that out safely","no":"We''ll use the hex wrench method"}}]'),

('garbage_disposal', 'Garbage disposal is leaking',
 '[{"cause":"Loose sink flange","difficulty":2,"steps":["Disconnect power","Place bucket underneath","Tighten mounting bolts","Apply plumber''s putty if needed","Reconnect and test"],"tools":["Wrench","Plumber''s putty"],"parts":["Plumber''s putty ~$5"],"safety":"Turn off power before working on unit"},{"cause":"Worn gasket/O-ring","difficulty":2,"steps":["Disconnect power and plumbing","Remove disposal unit","Replace rubber gasket","Reinstall","Test for leaks"],"tools":["Wrench","Screwdriver"],"parts":["Disposal gasket ~$8"],"safety":"Place bucket to catch water"}]',
 '[{"q":"Where is the leak coming from — top (sink connection), side (dishwasher connection), or bottom?","followup":{"top":"Likely the sink flange seal","side":"Dishwasher hose connection","bottom":"Internal seal failure — may need replacement"}},{"q":"Is the leak constant or only when running?","followup":{"constant":"Connection issue","only when running":"Seal or gasket problem"}}]'),

-- WATER HEATER (4)
('water_heater', 'No hot water',
 '[{"cause":"Pilot light out (gas)","difficulty":1,"steps":["Locate pilot light window","Check if flame is visible","Follow relighting instructions on unit label","Set to PILOT, hold button, use igniter","Hold 30-60 seconds, release, set to ON"],"tools":["Long lighter (backup)"],"parts":[],"safety":"⚠️ If you smell gas, STOP IMMEDIATELY. Leave the house. Call 911 and your gas company. Do NOT flip any switches."},{"cause":"Tripped breaker (electric)","difficulty":1,"steps":["Check electrical panel","Find water heater breaker","Reset if tripped","Wait 30 min for water to heat"],"tools":[],"parts":[],"safety":"Do not touch panel with wet hands"},{"cause":"Failed heating element (electric)","difficulty":4,"steps":["Turn off breaker","Drain tank partially","Remove access panel","Test element with multimeter","Replace if no continuity"],"tools":["Multimeter","Socket wrench","Garden hose"],"parts":["Heating element ~$15-25"],"safety":"MUST turn off power. Pro recommended for most homeowners."}]',
 '[{"q":"Is your water heater gas or electric?","followup":{"gas":"Let''s check the pilot light first","electric":"Let''s check the breaker"}},{"q":"Do you smell any gas near the water heater?","followup":{"yes":"🚨 STOP. Leave your home immediately and call 911. Do not touch any switches.","no":"Good. Let''s continue troubleshooting."}}]'),

('water_heater', 'Water not hot enough',
 '[{"cause":"Thermostat set too low","difficulty":1,"steps":["Locate temperature dial on water heater","Adjust to 120°F (recommended)","Wait 2-3 hours to test"],"tools":[],"parts":[],"safety":"Be careful of hot surfaces"},{"cause":"Sediment buildup","difficulty":2,"steps":["Turn off heater (gas: pilot, electric: breaker)","Connect garden hose to drain valve","Run to exterior drain","Flush until water runs clear","Close valve, refill, restart"],"tools":["Garden hose"],"parts":[],"safety":"Water will be very hot — use gloves. Route hose where hot water won''t cause injury."}]',
 '[{"q":"When was the last time the tank was flushed/drained?","followup":{"never":"Sediment buildup is very likely","recently":"May be a thermostat issue"}},{"q":"Is the water lukewarm or completely cold?","followup":{"lukewarm":"Thermostat or sediment issue","cold":"Heating element or pilot light"}}]'),

('water_heater', 'Water heater making popping/rumbling noises',
 '[{"cause":"Sediment buildup on heating elements","difficulty":2,"steps":["Turn off heater","Connect hose to drain valve","Flush 3-5 gallons","Repeat until clear","Restart heater"],"tools":["Garden hose"],"parts":[],"safety":"Hot water hazard — wear gloves and route hose carefully"}]',
 '[{"q":"How old is your water heater?","followup":{"old":"Sediment buildup is common in older units","new":"Unusual — may need pro inspection"}},{"q":"Has it ever been flushed/drained?","followup":{"yes":"When was the last time?","no":"That''s very likely the cause — sediment builds up over time"}}]'),

('water_heater', 'Water heater leaking from base',
 '[{"cause":"Corroded tank","difficulty":5,"steps":["Turn off water supply to heater","Turn off power/gas","This typically means the tank has failed and needs full replacement"],"tools":[],"parts":["New water heater $500-1500+"],"safety":"⚠️ PRO RECOMMENDED. Water heater replacement involves gas/electrical connections and proper venting. I strongly suggest booking a pro for this one."}]',
 '[{"q":"Is the water coming from the tank itself or from a pipe/valve connection?","followup":{"tank":"Tank corrosion — likely needs replacement (pro job)","pipe":"Connection issue — may be fixable"}},{"q":"How old is the unit?","followup":{"old":"Tanks typically last 8-12 years. Replacement is likely needed.","new":"Check warranty — may be covered"}}]'),

-- HVAC (3)
('hvac', 'AC not cooling',
 '[{"cause":"Dirty air filter","difficulty":1,"steps":["Locate return air vent or filter slot","Remove old filter","Note size printed on frame","Insert new filter with arrow pointing toward unit","Run AC for 30 min and check"],"tools":[],"parts":["Air filter ~$5-20"],"safety":"Turn off system before changing filter"},{"cause":"Thermostat issue","difficulty":1,"steps":["Check thermostat batteries","Ensure set to COOL mode","Set temperature below current room temp","Switch fan to AUTO","Wait 5 minutes"],"tools":[],"parts":["Batteries if needed"],"safety":"None"},{"cause":"Frozen evaporator coil","difficulty":2,"steps":["Turn AC OFF but fan ON","Let run for 2-3 hours to thaw","Check and replace air filter","If it refreezes, call a pro (refrigerant issue)"],"tools":[],"parts":[],"safety":"Do not try to chip ice off coils"}]',
 '[{"q":"When was the last time you changed the air filter?","followup":{"recently":"Filter is probably fine, let''s check other things","long ago":"That''s likely the issue — a clogged filter restricts airflow"}},{"q":"Is the outdoor unit running (fan spinning)?","followup":{"yes":"Compressor is working — issue may be inside","no":"Could be a breaker, capacitor, or compressor issue — may need a pro"}}]'),

('hvac', 'Furnace not heating',
 '[{"cause":"Dirty filter restricting airflow","difficulty":1,"steps":["Locate and remove air filter","Replace with correct size","Restart furnace"],"tools":[],"parts":["Air filter ~$5-20"],"safety":"Turn off system before changing filter"},{"cause":"Thermostat misconfigured","difficulty":1,"steps":["Set to HEAT mode","Set temperature above current room temp","Check batteries","Ensure fan is on AUTO"],"tools":[],"parts":[],"safety":"None"},{"cause":"Pilot light out (gas furnace)","difficulty":2,"steps":["Find pilot light assembly","Follow manufacturer relighting instructions","Set to PILOT, hold, ignite, wait 60s, set to ON"],"tools":["Long lighter"],"parts":[],"safety":"⚠️ If you smell gas, STOP. Leave immediately and call 911."}]',
 '[{"q":"Do you smell gas anywhere near the furnace?","followup":{"yes":"🚨 STOP. Leave your home NOW and call 911. Do not touch anything.","no":"Good. Let''s troubleshoot safely."}},{"q":"Is the thermostat display on?","followup":{"yes":"Good — it has power","no":"Check batteries or breaker"}}]'),

('hvac', 'HVAC making strange noises',
 '[{"cause":"Loose blower belt or bearing","difficulty":3,"steps":["Turn off system","Remove access panel","Inspect blower belt for wear/looseness","Tighten or replace belt","Lubricate bearings if accessible"],"tools":["Screwdriver","Wrench"],"parts":["Blower belt ~$10-20"],"safety":"Ensure system is OFF. If motor area, recommend pro."},{"cause":"Debris in outdoor unit","difficulty":1,"steps":["Turn off outdoor unit","Remove top grille (screws)","Clear leaves/sticks/debris","Replace grille","Restart"],"tools":["Screwdriver","Gloves"],"parts":[],"safety":"Ensure unit is powered off before opening"}]',
 '[{"q":"What kind of noise — squealing, banging, rattling, or grinding?","followup":{"squealing":"Likely a belt issue","banging":"Loose component or broken part","rattling":"Debris or loose panel","grinding":"Bearing issue — pro recommended"}},{"q":"Is the noise coming from inside or the outdoor unit?","followup":{"inside":"Blower motor area","outside":"Compressor/fan area"}}]'),

-- TOILET (3)
('toilet', 'Toilet keeps running',
 '[{"cause":"Flapper not sealing","difficulty":1,"steps":["Remove tank lid carefully","Check the rubber flapper at the bottom","If warped/worn, unhook old flapper","Take to hardware store for match","Hook new flapper on, attach chain","Adjust chain length — 1/2 inch slack"],"tools":[],"parts":["Toilet flapper ~$5-8"],"safety":"No safety concerns — just water. Turn off supply valve if needed."},{"cause":"Float set too high","difficulty":1,"steps":["Remove tank lid","Locate float (ball or cup type)","Adjust float down so water stops 1 inch below overflow tube","For ball float: bend rod down slightly","For cup float: pinch clip and slide down"],"tools":[],"parts":[],"safety":"None"}]',
 '[{"q":"If you remove the tank lid and press down on the flapper, does the running stop?","followup":{"yes":"The flapper needs replacement — super easy fix!","no":"Might be the fill valve or float"}},{"q":"Is water flowing into the overflow tube?","followup":{"yes":"Float is set too high","no":"Flapper seal issue"}}]'),

('toilet', 'Toilet is clogged',
 '[{"cause":"Standard clog","difficulty":1,"steps":["Use a flange plunger (the kind with the extra flap)","Place plunger over drain hole creating a seal","Push and pull vigorously 15-20 times","Flush to test","Repeat if needed"],"tools":["Flange plunger"],"parts":[],"safety":"Wear gloves. If water is near rim, wait 10 min for level to drop before plunging."},{"cause":"Deep clog","difficulty":2,"steps":["If plunger doesn''t work, use a toilet auger/snake","Insert auger into drain","Crank handle while pushing forward","Pull back to retrieve or push through clog","Flush to test"],"tools":["Toilet auger/snake ~$15-30"],"parts":[],"safety":"Do not use chemical drain cleaners in toilets — they can damage porcelain and seals"}]',
 '[{"q":"Have you tried plunging with a flange plunger (one with the extra flap)?","followup":{"yes":"How long did you try? Sometimes it takes 20+ firm plunges.","no":"That''s the best first step — let me walk you through it"}},{"q":"Is this a recurring problem?","followup":{"yes":"May have a deeper blockage in the drain line — could need a pro with a camera","no":"Likely a one-time clog we can clear"}}]'),

('toilet', 'Toilet leaking at base',
 '[{"cause":"Failed wax ring seal","difficulty":3,"steps":["Turn off water supply valve","Flush and sponge out remaining water","Disconnect supply line","Remove bolt caps and nuts at base","Lift toilet straight up and set aside on towels","Scrape old wax ring off flange and toilet bottom","Press new wax ring onto flange","Lower toilet onto bolts, press down firmly","Hand-tighten nuts evenly, then snug with wrench","Reconnect supply line, turn on water, test"],"tools":["Adjustable wrench","Putty knife","Towels","Bucket"],"parts":["Wax ring ~$5","Toilet bolt set ~$5"],"safety":"Toilet is heavy (~60 lbs). Get a helper. Wear gloves — sewer gas."}]',
 '[{"q":"Is the water clear or discolored?","followup":{"clear":"Could be condensation or supply line leak","discolored":"Wax ring failure — needs replacement"}},{"q":"Does it leak all the time or only when flushing?","followup":{"always":"Supply line or condensation","only flushing":"Wax ring is the likely culprit"}}]'),

-- GARAGE DOOR (3)
('garage_door', 'Garage door won''t open or close',
 '[{"cause":"Dead remote batteries","difficulty":1,"steps":["Replace batteries in remote","Test remote","Check wall button — if wall button works, remote was the issue"],"tools":[],"parts":["Remote batteries ~$3"],"safety":"None"},{"cause":"Misaligned safety sensors","difficulty":1,"steps":["Check the two sensors at bottom of door tracks","Ensure both have steady lights (not blinking)","Clean sensor eyes with soft cloth","Adjust alignment until lights are steady","Test door"],"tools":["Soft cloth"],"parts":[],"safety":"Do not block sensors while door is moving"},{"cause":"Broken torsion spring","difficulty":5,"steps":["🚫 DO NOT attempt to repair torsion springs yourself","These are under extreme tension and can cause serious injury or death","Call a professional garage door technician"],"tools":[],"parts":[],"safety":"🚨 DANGER: Torsion springs are under extreme tension. This is a PRO ONLY repair. Attempting this yourself can result in serious injury or death."}]',
 '[{"q":"Does the wall-mounted button work, or is it just the remote?","followup":{"wall works":"Just need new remote batteries","neither works":"Could be power, sensor, or mechanical issue"}},{"q":"Do you see a broken spring above the door (a gap in the coiled metal bar)?","followup":{"yes":"🚨 That''s a torsion spring — DO NOT touch it. This needs a pro. I''ll get you a quote.","no":"Good. Let''s check the sensors."}}]'),

('garage_door', 'Garage door is noisy/squeaking',
 '[{"cause":"Dry rollers and hinges","difficulty":1,"steps":["Buy white lithium grease or garage door lubricant","Spray all roller bearings","Spray all hinge pivot points","Spray the torsion spring coils","Open and close door 2-3 times to distribute"],"tools":["Garage door lubricant or white lithium grease"],"parts":["Lubricant ~$6"],"safety":"Do not touch torsion springs — just spray them. Keep hands clear of moving parts."},{"cause":"Worn rollers","difficulty":2,"steps":["Inspect rollers for cracks or flat spots","Replace worn rollers one at a time","Remove hinge bolt, slide out old roller, insert new","NEVER remove the bottom roller brackets — they''re under spring tension"],"tools":["Socket wrench","Replacement rollers"],"parts":["Nylon rollers ~$5 each"],"safety":"⚠️ NEVER remove bottom bracket rollers — attached to spring cables. Top and middle only."}]',
 '[{"q":"Is the noise a squeak, grinding, or banging?","followup":{"squeak":"Likely needs lubrication — easy fix","grinding":"Worn rollers or track issue","banging":"Loose hardware or balance problem"}},{"q":"When was the last time you lubricated the moving parts?","followup":{"recently":"May be worn parts","never":"Lubrication will likely fix it"}}]'),

('garage_door', 'Garage door reverses before closing',
 '[{"cause":"Misaligned photo-eye sensors","difficulty":1,"steps":["Check both sensors at bottom of tracks","One should have green light, one amber","If blinking, they''re misaligned","Loosen wing nut, adjust until solid light","Tighten and test"],"tools":[],"parts":[],"safety":"Keep clear of door while testing"},{"cause":"Close-limit needs adjustment","difficulty":2,"steps":["Locate the opener unit on ceiling","Find the limit adjustment screws (usually labeled)","Turn close-limit screw clockwise in small increments","Test door after each adjustment"],"tools":["Stepladder"],"parts":[],"safety":"Use stable ladder. Keep hands away from moving parts."}]',
 '[{"q":"Does the door start to close then reverse, or does it not move at all?","followup":{"starts then reverses":"Sensor or limit switch issue","no movement":"Different problem — power or remote issue"}},{"q":"Are both sensor lights solid (not blinking)?","followup":{"yes":"Likely a close-limit adjustment","no":"Sensor alignment is the issue — easy fix"}}]'),

-- FAUCET (3)
('faucet', 'Faucet is dripping',
 '[{"cause":"Worn cartridge or washer","difficulty":2,"steps":["Turn off water supply under sink","Open faucet to release pressure","Remove handle (screw under cap or set screw)","Pull out cartridge or stem","Take old part to hardware store for exact match","Install new cartridge/washer","Reassemble, turn on water, test"],"tools":["Screwdriver","Adjustable wrench","Allen key set"],"parts":["Faucet cartridge/washer ~$5-20"],"safety":"Turn off supply valves first. Have towels ready."},{"cause":"Worn O-rings","difficulty":2,"steps":["Turn off water supply","Disassemble faucet handle","Locate O-rings on stem","Pry off with flat screwdriver","Coat new O-rings with plumber''s grease","Reassemble"],"tools":["Screwdriver","Needle-nose pliers"],"parts":["O-ring set ~$3-5","Plumber''s grease ~$4"],"safety":"Turn off supply valves. No safety concerns."}]',
 '[{"q":"Is it a single-handle or two-handle faucet?","followup":{"single":"Likely a cartridge issue","two":"Could be washer or seat — which side drips (hot or cold)?"}},{"q":"How fast is the drip — occasional or constant stream?","followup":{"occasional":"Minor wear — easy fix","constant":"More significant wear but still fixable"}}]'),

('faucet', 'Low water pressure at faucet',
 '[{"cause":"Clogged aerator","difficulty":1,"steps":["Unscrew the aerator from faucet tip (hand-tight usually)","Use pliers with cloth if stuck","Disassemble aerator screen pieces","Soak in white vinegar for 30 minutes","Scrub with old toothbrush","Reassemble and screw back on"],"tools":["Pliers","Old toothbrush"],"parts":["White vinegar"],"safety":"None"},{"cause":"Partially closed supply valve","difficulty":1,"steps":["Check under sink for supply valves","Ensure both are fully open (counter-clockwise)","Test flow"],"tools":[],"parts":[],"safety":"None"}]',
 '[{"q":"Is the low pressure in just this faucet or throughout the house?","followup":{"just this one":"Likely a clogged aerator — very easy fix","whole house":"Could be a main valve or municipal issue — different problem"}},{"q":"Has the pressure gradually decreased or suddenly dropped?","followup":{"gradually":"Mineral buildup in aerator","suddenly":"Check if a valve got partially closed"}}]'),

('faucet', 'Faucet handle is loose or hard to turn',
 '[{"cause":"Loose handle screw","difficulty":1,"steps":["Pop off decorative cap on handle","Tighten the screw underneath","Replace cap","Test handle"],"tools":["Screwdriver or Allen key"],"parts":[],"safety":"None"},{"cause":"Mineral buildup in cartridge","difficulty":2,"steps":["Turn off supply valves","Remove handle and cartridge","Soak cartridge in vinegar 1-2 hours","Clean with brush","Apply silicone grease","Reassemble"],"tools":["Screwdriver","Pliers"],"parts":["Silicone grease ~$5"],"safety":"Turn off water first"}]',
 '[{"q":"Is the handle loose/wobbly, or stiff/hard to turn?","followup":{"loose":"Likely just needs a screw tightened","hard to turn":"Mineral buildup or worn cartridge"}},{"q":"Is it the hot, cold, or both handles?","followup":{"both":"Mineral buildup throughout","one":"That specific valve needs attention"}}]'),

-- DISHWASHER (3)
('dishwasher', 'Dishwasher not draining',
 '[{"cause":"Clogged filter/drain basket","difficulty":1,"steps":["Remove bottom rack","Locate and remove the filter/drain basket (twist counterclockwise usually)","Clean under running water with brush","Check drain area for debris","Reinstall filter","Run a short cycle"],"tools":["Soft brush"],"parts":[],"safety":"Disconnect power or turn off breaker before reaching into drain area"},{"cause":"Kinked or clogged drain hose","difficulty":2,"steps":["Pull dishwasher out slightly","Check drain hose for kinks","Straighten if kinked","Disconnect at sink/disposal connection and clear clogs","Reconnect and test"],"tools":["Pliers","Bucket","Towels"],"parts":[],"safety":"Turn off power and water before pulling unit out"}]',
 '[{"q":"Is there standing water in the bottom of the dishwasher?","followup":{"yes":"Drain is blocked somewhere — let''s find it","no":"May be a pump issue"}},{"q":"Do you have a garbage disposal? If so, is it clear?","followup":{"yes with disposal":"Run the disposal first — dishwasher often drains through it","no disposal":"Let''s check the air gap or drain hose"}}]'),

('dishwasher', 'Dishwasher not cleaning well',
 '[{"cause":"Clogged spray arms","difficulty":1,"steps":["Remove spray arms (twist or unclip)","Clear holes with toothpick or wire","Soak in vinegar if mineral buildup is heavy","Rinse and reinstall","Run hot empty cycle with cup of vinegar"],"tools":["Toothpick or thin wire"],"parts":[],"safety":"None"},{"cause":"Water not hot enough","difficulty":1,"steps":["Run kitchen hot water tap until hot BEFORE starting dishwasher","Check water heater temperature (should be 120°F)","Use heated dry option if available"],"tools":[],"parts":[],"safety":"None"}]',
 '[{"q":"Do you see food particles still on dishes or a white film?","followup":{"food particles":"Spray arms or filter issue","white film":"Hard water — need rinse aid or vinegar"}},{"q":"Do you run hot water at the sink before starting the dishwasher?","followup":{"yes":"Let''s check spray arms and filter","no":"Try that first — dishwasher needs hot water from the start"}}]'),

('dishwasher', 'Dishwasher is leaking',
 '[{"cause":"Worn door gasket","difficulty":2,"steps":["Inspect the rubber gasket around door edge","Clean with warm soapy water","If cracked/worn, peel off old gasket","Press new gasket into channel","Close door to set shape"],"tools":[],"parts":["Door gasket ~$15-30 (model-specific)"],"safety":"Disconnect power before any repair"},{"cause":"Loose or cracked hose connection","difficulty":2,"steps":["Turn off power and water supply","Pull dishwasher out carefully","Inspect water supply and drain hoses","Tighten clamps or replace cracked hoses","Push back in and test"],"tools":["Screwdriver","Pliers"],"parts":["Hose clamps ~$3"],"safety":"⚠️ Standing water near electrical connections — turn off breaker first!"}]',
 '[{"q":"Where is the water — in front of the door or underneath?","followup":{"front":"Door gasket issue","underneath":"Hose or connection leak"}},{"q":"Does it leak during washing or all the time?","followup":{"during washing":"Active leak — gasket, spray arm, or overfill","all the time":"Water supply connection"}}]'),

-- WASHER (3)
('washer', 'Washing machine won''t drain',
 '[{"cause":"Clogged drain filter/pump filter","difficulty":1,"steps":["Locate drain filter (usually front bottom behind small panel)","Place towels and shallow pan underneath","Slowly open filter — water WILL come out","Clean filter of lint, coins, small items","Reinstall filter hand-tight","Run spin cycle to test"],"tools":["Towels","Shallow pan"],"parts":[],"safety":"Expect a lot of water when opening filter. Have towels ready."},{"cause":"Kinked drain hose","difficulty":1,"steps":["Pull machine from wall slightly","Check drain hose for kinks","Straighten hose","Ensure hose end is 24-36 inches above floor in standpipe","Test with drain cycle"],"tools":[],"parts":[],"safety":"Unplug before moving machine"}]',
 '[{"q":"Is the machine making any humming or grinding sounds during the drain cycle?","followup":{"yes":"Pump may be clogged or failing","no":"Likely a drain hose issue"}},{"q":"Have you noticed small items (socks, coins) going missing in the wash?","followup":{"yes":"They''re probably in the pump filter!","no":"Still worth checking the filter"}}]'),

('washer', 'Washing machine is vibrating excessively',
 '[{"cause":"Machine not level","difficulty":1,"steps":["Place level on top of machine","Adjust feet by turning them (most screw in/out)","Check front-to-back AND side-to-side","Lock nuts against machine base when level","Test with spin cycle"],"tools":["Bubble level"],"parts":[],"safety":"Unplug before adjusting feet"},{"cause":"Unbalanced load","difficulty":1,"steps":["Stop the cycle","Open and redistribute clothes evenly","Don''t overload — fill loosely to top of drum","Resume cycle"],"tools":[],"parts":[],"safety":"Wait for drum to stop before opening"}]',
 '[{"q":"Does it vibrate on every load or just sometimes?","followup":{"every":"Machine likely not level","sometimes":"Load distribution issue"}},{"q":"Is the machine on a level surface?","followup":{"yes":"Let''s check the leveling feet","no":"That''s the issue — we need to level it"}}]'),

('washer', 'Washing machine smells musty',
 '[{"cause":"Mold/mildew buildup","difficulty":1,"steps":["Run empty hot cycle with 2 cups white vinegar","Follow with another empty hot cycle with 1/2 cup baking soda","Clean rubber door gasket with vinegar solution","Leave door open between uses","Clean detergent dispenser drawer"],"tools":["Soft cloth"],"parts":["White vinegar","Baking soda"],"safety":"None — just cleaning"},{"cause":"Clogged drain filter","difficulty":1,"steps":["Locate and clean pump filter (front bottom)","Clean drain filter of trapped lint and debris","Run a hot clean cycle after"],"tools":["Towels"],"parts":[],"safety":"Water will drain when opening filter"}]',
 '[{"q":"Do you have a front-loader or top-loader?","followup":{"front":"Front-loaders are notorious for this — the door gasket traps moisture","top":"Less common — check if drain filter is clogged"}},{"q":"Do you leave the door open between loads?","followup":{"yes":"Good habit. Let''s do a deep clean.","no":"That''s the #1 cause — moisture gets trapped and breeds mold"}}]'),

-- DRYER (3)
('dryer', 'Dryer not heating',
 '[{"cause":"Clogged lint trap/vent","difficulty":1,"steps":["Clean lint trap thoroughly","Check external vent flap outside house","Disconnect vent hose from back of dryer","Clean hose with vent brush or vacuum","Clean vent duct if accessible","Reconnect and test"],"tools":["Dryer vent brush kit ~$10","Vacuum"],"parts":[],"safety":"Unplug dryer before disconnecting vent. Clogged vents are a FIRE HAZARD."},{"cause":"Tripped breaker (electric dryer)","difficulty":1,"steps":["Electric dryers use TWO breaker slots (240V)","Check both are fully in ON position","Reset both","Test dryer"],"tools":[],"parts":[],"safety":"Do not touch panel with wet hands"},{"cause":"Failed thermal fuse","difficulty":3,"steps":["Unplug dryer","Remove back panel","Locate thermal fuse on exhaust duct","Test with multimeter for continuity","Replace if blown","⚠️ Also clean vent — a blown fuse means vent was clogged"],"tools":["Screwdriver","Multimeter"],"parts":["Thermal fuse ~$5-15"],"safety":"Must unplug before any internal work"}]',
 '[{"q":"Is the dryer tumbling but just not getting hot?","followup":{"yes":"Heating element, thermal fuse, or gas igniter issue","no":"If not tumbling at all, different issue — could be belt or motor"}},{"q":"When was the last time you cleaned the dryer vent hose (not just the lint trap)?","followup":{"recently":"Thermal fuse or element likely","never":"🔥 That''s likely the cause AND a fire hazard. Let''s fix this now."}}]'),

('dryer', 'Dryer takes too long to dry',
 '[{"cause":"Clogged vent system","difficulty":1,"steps":["Clean lint trap","Disconnect vent hose from dryer","Clean entire hose length","Check outside vent flap opens freely","Consider replacing flexible foil hose with rigid metal duct","Reconnect and test"],"tools":["Vent brush kit","Vacuum"],"parts":["Rigid metal duct ~$15 (if replacing flex hose)"],"safety":"Unplug before working on vent. THIS IS A FIRE SAFETY ISSUE."},{"cause":"Overloaded drum","difficulty":1,"steps":["Dry smaller loads","Ensure clothes are spun well in washer first","Don''t overfill past 3/4 full","Separate heavy items (towels) from light items"],"tools":[],"parts":[],"safety":"None"}]',
 '[{"q":"Does the outside vent flap open when dryer is running?","followup":{"yes":"Some airflow — may be partial clog","no":"Vent is clogged — fire hazard, let''s fix it now"}},{"q":"Are you drying full loads or smaller loads?","followup":{"full":"Try smaller loads and see if that helps","small":"Definitely a vent or heating issue"}}]'),

('dryer', 'Dryer making loud noise',
 '[{"cause":"Worn drum support rollers","difficulty":3,"steps":["Unplug dryer","Remove front or top panel (model-dependent)","Remove drum belt and drum","Inspect rollers — if flat-spotted or wobbling, replace","Replace in pairs","Reassemble"],"tools":["Screwdriver","Socket set","Putty knife"],"parts":["Drum rollers ~$15-25 pair"],"safety":"Unplug dryer. Note screw locations for reassembly."},{"cause":"Foreign object in drum","difficulty":1,"steps":["Check drum for loose items (coins, buttons, zippers)","Check rubber seal/baffle for trapped items","Run empty to test"],"tools":[],"parts":[],"safety":"None"}]',
 '[{"q":"What does the noise sound like — squealing, thumping, or scraping?","followup":{"squealing":"Belt or idler pulley","thumping":"Drum rollers or support","scraping":"Something caught or worn drum glide"}},{"q":"Does the noise happen when the dryer is empty?","followup":{"yes":"Internal component issue","no":"May be items in the load causing it"}}]'),

-- ELECTRICAL (3)
('electrical', 'Outlet not working',
 '[{"cause":"Tripped GFCI outlet","difficulty":1,"steps":["Look for GFCI outlets in kitchen, bathroom, garage, exterior","Press RESET button on the GFCI outlet","Test the dead outlet","One GFCI can protect multiple outlets downstream"],"tools":[],"parts":[],"safety":"Do not use if outlet looks scorched, melted, or smells burnt — call a pro."},{"cause":"Tripped breaker","difficulty":1,"steps":["Go to electrical panel","Look for breaker that''s in middle position or OFF","Flip fully OFF then back ON","Test outlet"],"tools":[],"parts":[],"safety":"Do not touch panel with wet hands. If breaker keeps tripping, call a pro — could be a wiring issue."},{"cause":"Loose wire connection","difficulty":5,"steps":["🚫 DO NOT attempt to open outlets or work on wiring yourself","Electrical wiring requires a licensed electrician","Improper wiring can cause fires and electrocution"],"tools":[],"parts":[],"safety":"🚨 PRO ONLY: Electrical wiring work should only be done by a licensed electrician. Risk of electrocution and fire."}]',
 '[{"q":"Is it just one outlet or multiple outlets that stopped working?","followup":{"one":"Let''s check for a tripped GFCI first","multiple":"Likely a tripped breaker or GFCI"}},{"q":"Do you see any scorch marks, smell burning, or is the outlet warm to the touch?","followup":{"yes":"🚨 STOP using that outlet. Do not plug anything in. Call an electrician immediately. This is a fire hazard.","no":"Good. Let''s check GFCI and breaker."}}]'),

('electrical', 'Light fixture flickering',
 '[{"cause":"Loose bulb","difficulty":1,"steps":["Turn off the light switch","Wait for bulb to cool","Tighten bulb in socket","Turn switch on and test"],"tools":[],"parts":[],"safety":"Ensure switch is off. Let bulb cool before touching."},{"cause":"Bad bulb or incompatible dimmer","difficulty":1,"steps":["Replace bulb with known working one","If on a dimmer, ensure bulbs are dimmer-compatible (check package)","LED bulbs need LED-compatible dimmers"],"tools":[],"parts":["Replacement bulb ~$3-10"],"safety":"Turn off switch before changing bulbs"},{"cause":"Loose wiring","difficulty":5,"steps":["🚫 DO NOT open electrical fixtures or junction boxes","Loose wiring is a fire hazard and requires a licensed electrician"],"tools":[],"parts":[],"safety":"🚨 PRO ONLY: If tightening bulb doesn''t fix it, call an electrician. Loose wiring causes fires."}]',
 '[{"q":"Is it just one light or multiple lights flickering?","followup":{"one":"Likely the bulb or fixture","multiple":"Could be a circuit issue — worth checking breaker panel"}},{"q":"Is the light on a dimmer switch?","followup":{"yes":"Make sure the bulbs are dimmer-compatible — this is very common with LEDs","no":"Let''s try tightening or replacing the bulb first"}}]'),

('electrical', 'Circuit breaker keeps tripping',
 '[{"cause":"Overloaded circuit","difficulty":1,"steps":["Identify what''s on that circuit","Unplug some devices to reduce load","Spread high-draw appliances across different circuits","Space heaters, hair dryers, and microwaves are common culprits"],"tools":[],"parts":[],"safety":"If it keeps tripping after reducing load, call a pro — could be a wiring fault."},{"cause":"Short circuit or ground fault","difficulty":5,"steps":["🚫 DO NOT attempt to diagnose wiring faults yourself","A repeatedly tripping breaker can indicate serious wiring problems","Call a licensed electrician for diagnosis"],"tools":[],"parts":[],"safety":"🚨 PRO REQUIRED: Repeatedly tripping breakers can indicate a dangerous wiring fault, loose connection, or damaged wire. This needs professional diagnosis to prevent fire."}]',
 '[{"q":"Does it trip immediately when you reset it, or after a while?","followup":{"immediately":"Short circuit — call a pro. Do not keep resetting.","after a while":"Overloaded circuit — too many things plugged in"}},{"q":"Do you know which appliances are on that circuit?","followup":{"yes":"Let''s see if it''s overloaded — tell me what''s plugged in","no":"Try unplugging things one at a time and resetting to find the culprit"}}]');
